`include "DifftestMacros.svh"

module SimTop_wrapper(
  input           inter_soc_clk,
  input           sys_rstn_i,
  input           tmclk,

  input           global_reset,     //24MHz

  input  [3:0]    pll_bypass_sel,   //apb clk : 100MHz
  output          pll0_lock,
  output          pll0_clk_div_1024,
  output [11:0]   pll0_test_calout,

  input  [15:0]   soc_to_cpu,   // none
  output [15:0]   cpu_to_soc,   //none

  input  [63:0]   io_extIntrs,   // come from IPs, Max : 600MHz

  input  [15:0]   io_sram_config,  //apb clk : 100MHz

  input           io_systemjtag_jtag_TCK,         // come from gpio
  input           io_systemjtag_jtag_TMS,         // come from gpio
  input           io_systemjtag_jtag_TDI,         // come from gpio
  output          io_systemjtag_jtag_TDO_data,    // come from gpio
  output          io_systemjtag_jtag_TDO_driven,  // come from gpio
  input           io_systemjtag_reset,            // come from gpio

// peri bus   //400MHz
// dma bus    //800MHz
// mem bus    //800MHz

  (*mark_debug="true"*) output          dma_core_awready,
  (*mark_debug="true"*) input           dma_core_awvalid,
  (*mark_debug="true"*) input  [13:0]   dma_core_awid,
  (*mark_debug="true"*) input  [35:0]   dma_core_awaddr,
  (*mark_debug="true"*) input  [7:0]    dma_core_awlen,
  (*mark_debug="true"*) input  [2:0]    dma_core_awsize,
  (*mark_debug="true"*) input  [1:0]    dma_core_awburst,
  (*mark_debug="true"*) input           dma_core_awlock,
  (*mark_debug="true"*) input  [3:0]    dma_core_awcache,
  (*mark_debug="true"*) input  [2:0]    dma_core_awprot,
  (*mark_debug="true"*) input  [3:0]    dma_core_awqos,
  (*mark_debug="true"*) output          dma_core_wready,
  (*mark_debug="true"*) input           dma_core_wvalid,
  (*mark_debug="true"*) input  [255:0]  dma_core_wdata,
  (*mark_debug="true"*) input  [31:0]   dma_core_wstrb,
  (*mark_debug="true"*) input           dma_core_wlast,
  (*mark_debug="true"*) input           dma_core_bready,
  (*mark_debug="true"*) output          dma_core_bvalid,
  (*mark_debug="true"*) output [13:0]   dma_core_bid,
  (*mark_debug="true"*) output [1:0]    dma_core_bresp,
  (*mark_debug="true"*) output          dma_core_arready,
  (*mark_debug="true"*) input           dma_core_arvalid,
  (*mark_debug="true"*) input  [13:0]   dma_core_arid,
  (*mark_debug="true"*) input  [35:0]   dma_core_araddr,
  (*mark_debug="true"*) input  [7:0]    dma_core_arlen,
  (*mark_debug="true"*) input  [2:0]    dma_core_arsize,
  (*mark_debug="true"*) input  [1:0]    dma_core_arburst,
  (*mark_debug="true"*) input           dma_core_arlock,
  (*mark_debug="true"*) input  [3:0]    dma_core_arcache,
  (*mark_debug="true"*) input  [2:0]    dma_core_arprot,
  (*mark_debug="true"*) input  [3:0]    dma_core_arqos,
  (*mark_debug="true"*) input           dma_core_rready,
  (*mark_debug="true"*) output          dma_core_rvalid,
  (*mark_debug="true"*) output [13:0]   dma_core_rid,
  (*mark_debug="true"*) output [255:0]  dma_core_rdata,
  (*mark_debug="true"*) output [1:0]    dma_core_rresp,
  (*mark_debug="true"*) output          dma_core_rlast,

  (*mark_debug="true"*) input           peri_awready,
  (*mark_debug="true"*) output          peri_awvalid,
  (*mark_debug="true"*) output [1:0]    peri_awid,
  (*mark_debug="true"*) output [30:0]   peri_awaddr,
  (*mark_debug="true"*) output [7:0]    peri_awlen,
  (*mark_debug="true"*) output [2:0]    peri_awsize,
  (*mark_debug="true"*) output [1:0]    peri_awburst,
  (*mark_debug="true"*) output          peri_awlock,
  (*mark_debug="true"*) output [3:0]    peri_awcache,
  (*mark_debug="true"*) output [2:0]    peri_awprot,
  (*mark_debug="true"*) output [3:0]    peri_awqos,
  (*mark_debug="true"*) input           peri_wready,
  (*mark_debug="true"*) output          peri_wvalid,
  (*mark_debug="true"*) output [63:0]   peri_wdata,
  (*mark_debug="true"*) output [7:0]    peri_wstrb,
  (*mark_debug="true"*) output          peri_wlast,
  (*mark_debug="true"*) output          peri_bready,
  (*mark_debug="true"*) input           peri_bvalid,
  (*mark_debug="true"*) input  [1:0]    peri_bid,
  (*mark_debug="true"*) input  [1:0]    peri_bresp,
  (*mark_debug="true"*) input           peri_arready,
  (*mark_debug="true"*) output          peri_arvalid,
  (*mark_debug="true"*) output [1:0]    peri_arid,
  (*mark_debug="true"*) output [30:0]   peri_araddr,
  (*mark_debug="true"*) output [7:0]    peri_arlen,
  (*mark_debug="true"*) output [2:0]    peri_arsize,
  (*mark_debug="true"*) output [1:0]    peri_arburst,
  (*mark_debug="true"*) output          peri_arlock,
  (*mark_debug="true"*) output [3:0]    peri_arcache,
  (*mark_debug="true"*) output [2:0]    peri_arprot,
  (*mark_debug="true"*) output [3:0]    peri_arqos,
  (*mark_debug="true"*) output          peri_rready,
  (*mark_debug="true"*) input           peri_rvalid,
  (*mark_debug="true"*) input  [1:0]    peri_rid,
  (*mark_debug="true"*) input  [63:0]   peri_rdata,
  (*mark_debug="true"*) input  [1:0]    peri_rresp,
  (*mark_debug="true"*) input           peri_rlast,

  (*mark_debug="true"*) input           mem_core_awready,
  (*mark_debug="true"*) output          mem_core_awvalid,
  (*mark_debug="true"*) output [13:0]   mem_core_awid,
  (*mark_debug="true"*) output [35:0]   mem_core_awaddr,
  (*mark_debug="true"*) output [7:0]    mem_core_awlen,
  (*mark_debug="true"*) output [2:0]    mem_core_awsize,
  (*mark_debug="true"*) output [1:0]    mem_core_awburst,
  (*mark_debug="true"*) output          mem_core_awlock,
  (*mark_debug="true"*) output [3:0]    mem_core_awcache,
  (*mark_debug="true"*) output [2:0]    mem_core_awprot,
  (*mark_debug="true"*) output [3:0]    mem_core_awqos,
  (*mark_debug="true"*) input           mem_core_wready,
  (*mark_debug="true"*) output          mem_core_wvalid,
  (*mark_debug="true"*) output [63:0]   mem_core_wdata,
  (*mark_debug="true"*) output [7:0]    mem_core_wstrb,
  (*mark_debug="true"*) output          mem_core_wlast,
  (*mark_debug="true"*) output          mem_core_bready,
  (*mark_debug="true"*) input           mem_core_bvalid,
  (*mark_debug="true"*) input  [17:0]   mem_core_bid,
  (*mark_debug="true"*) input  [1:0]    mem_core_bresp,
  (*mark_debug="true"*) input           mem_core_arready,
  (*mark_debug="true"*) output          mem_core_arvalid,
  (*mark_debug="true"*) output [13:0]   mem_core_arid,
  (*mark_debug="true"*) output [35:0]   mem_core_araddr,
  (*mark_debug="true"*) output [7:0]    mem_core_arlen,
  (*mark_debug="true"*) output [2:0]    mem_core_arsize,
  (*mark_debug="true"*) output [1:0]    mem_core_arburst,
  (*mark_debug="true"*) output          mem_core_arlock,
  (*mark_debug="true"*) output [3:0]    mem_core_arcache,
  (*mark_debug="true"*) output [2:0]    mem_core_arprot,
  (*mark_debug="true"*) output [3:0]    mem_core_arqos,
  (*mark_debug="true"*) output          mem_core_rready,
  (*mark_debug="true"*) input           mem_core_rvalid,
  (*mark_debug="true"*) input  [17:0]   mem_core_rid,
  (*mark_debug="true"*) input  [63:0]   mem_core_rdata,
  (*mark_debug="true"*) input  [1:0]    mem_core_rresp,
  (*mark_debug="true"*) input           mem_core_rlast,

input          difftest_ref_clock,
               difftest_ref_reset,
               difftest_pcie_clock,
input          difftest_to_host_axis_tready,
output         difftest_to_host_axis_tvalid,
output [`CONFIG_DIFFTEST_HOST_AXIS_WIDTH-1:0] difftest_to_host_axis_tdata,
output [`CONFIG_DIFFTEST_HOST_AXIS_BYTES-1:0] difftest_to_host_axis_tkeep,
output         difftest_to_host_axis_tlast,
output         difftest_from_host_axis_tready,
input          difftest_from_host_axis_tvalid,
input  [`CONFIG_DIFFTEST_HOST_AXIS_WIDTH-1:0] difftest_from_host_axis_tdata,
input  [`CONFIG_DIFFTEST_HOST_AXIS_BYTES-1:0] difftest_from_host_axis_tkeep,
input          difftest_from_host_axis_tlast,
output         difftest_clock_enable,
               difftest_hostCtrl_reset,
               difftest_hostCtrl_diffEnable,
               difftest_hostCtrl_ilaTrigger,
               difftest_hostCtrl_enableSquash,

input  [31:0]  difftest_cfg_axilite_awaddr,
input          difftest_cfg_axilite_awvalid,
output         difftest_cfg_axilite_awready,
input  [31:0]  difftest_cfg_axilite_wdata,
input  [3:0]   difftest_cfg_axilite_wstrb,
input          difftest_cfg_axilite_wvalid,
output         difftest_cfg_axilite_wready,
output [1:0]   difftest_cfg_axilite_bresp,
output         difftest_cfg_axilite_bvalid,
input          difftest_cfg_axilite_bready,
input  [31:0]  difftest_cfg_axilite_araddr,
input          difftest_cfg_axilite_arvalid,
output         difftest_cfg_axilite_arready,
output [31:0]  difftest_cfg_axilite_rdata,
output [1:0]   difftest_cfg_axilite_rresp,
output         difftest_cfg_axilite_rvalid,
input          difftest_cfg_axilite_rready
);

SimTop u_SimTop (
    .clock                      (inter_soc_clk),
    .reset                      (~sys_rstn_i),

    .difftest_exit              (),
    .difftest_step              (),
    .difftest_perfCtrl_clean    (1'b0),
    .difftest_perfCtrl_dump     (1'b0),
    .difftest_logCtrl_begin     (64'b0),
    .difftest_logCtrl_end       (64'hFFFFFFFFFFFFFFFF),
    .difftest_logCtrl_level     (64'b0),
    .difftest_uart_out_valid    (),
    .difftest_uart_out_ch       (),
    .difftest_uart_in_valid     (),
    .difftest_uart_in_ch        (8'b0),

    // AXI4 MEMORY (flattened port names)
    .difftest_mem_awready       (mem_core_awready),
    .difftest_mem_awvalid       (mem_core_awvalid),
    .difftest_mem_awaddr        (mem_core_awaddr[31:0]),
    .difftest_mem_awprot        (mem_core_awprot),
    .difftest_mem_awid          (mem_core_awid),
    .difftest_mem_awuser        (),
    .difftest_mem_awlen         (mem_core_awlen),
    .difftest_mem_awsize        (mem_core_awsize),
    .difftest_mem_awburst       (mem_core_awburst),
    .difftest_mem_awlock        (mem_core_awlock),
    .difftest_mem_awcache       (mem_core_awcache),
    .difftest_mem_awqos         (mem_core_awqos),

    .difftest_mem_wready        (mem_core_wready),
    .difftest_mem_wvalid        (mem_core_wvalid),
    .difftest_mem_wdata         (mem_core_wdata[63:0]),
    .difftest_mem_wstrb         (mem_core_wstrb[7:0]),
    .difftest_mem_wlast         (mem_core_wlast),

    .difftest_mem_bready        (mem_core_bready),
    .difftest_mem_bvalid        (mem_core_bvalid),
    .difftest_mem_bresp         (mem_core_bresp),
    .difftest_mem_bid           (mem_core_bid),
    .difftest_mem_buser         ('b0),

    .difftest_mem_arready       (mem_core_arready),
    .difftest_mem_arvalid       (mem_core_arvalid),
    .difftest_mem_araddr        (mem_core_araddr[31:0]),
    .difftest_mem_arprot        (mem_core_arprot),
    .difftest_mem_arid          (mem_core_arid),
    .difftest_mem_aruser        (),
    .difftest_mem_arlen         (mem_core_arlen),
    .difftest_mem_arsize        (mem_core_arsize),
    .difftest_mem_arburst       (mem_core_arburst),
    .difftest_mem_arlock        (mem_core_arlock),
    .difftest_mem_arcache       (mem_core_arcache),
    .difftest_mem_arqos         (mem_core_arqos),

    .difftest_mem_rready        (mem_core_rready),
    .difftest_mem_rvalid        (mem_core_rvalid),
    .difftest_mem_rresp         (mem_core_rresp),
    .difftest_mem_rdata         (mem_core_rdata[63:0]),
    .difftest_mem_rlast         (mem_core_rlast),
    .difftest_mem_rid           (mem_core_rid),
    .difftest_mem_ruser         ('b0),

    // AXI4 MMIO
    .io_mmio_aw_ready           (peri_awready),
    .io_mmio_aw_valid           (peri_awvalid),
    .io_mmio_aw_bits_addr       (peri_awaddr),
    .io_mmio_aw_bits_prot       (peri_awprot),
    .io_mmio_aw_bits_id         (peri_awid),
    .io_mmio_aw_bits_user       (),
    .io_mmio_aw_bits_len        (peri_awlen),
    .io_mmio_aw_bits_size       (peri_awsize),
    .io_mmio_aw_bits_burst      (peri_awburst),
    .io_mmio_aw_bits_lock       (peri_awlock),
    .io_mmio_aw_bits_cache      (peri_awcache),
    .io_mmio_aw_bits_qos        (peri_awqos),

    .io_mmio_w_ready            (peri_wready),
    .io_mmio_w_valid            (peri_wvalid),
    .io_mmio_w_bits_data        (peri_wdata),
    .io_mmio_w_bits_strb        (peri_wstrb),
    .io_mmio_w_bits_last        (peri_wlast),

    .io_mmio_b_ready            (peri_bready),
    .io_mmio_b_valid            (peri_bvalid),
    .io_mmio_b_bits_resp        (peri_bresp),
    .io_mmio_b_bits_id          (peri_bid),
    .io_mmio_b_bits_user        (1'b0),

    .io_mmio_ar_ready           (peri_arready),
    .io_mmio_ar_valid           (peri_arvalid),
    .io_mmio_ar_bits_addr       (peri_araddr),
    .io_mmio_ar_bits_prot       (peri_arprot),
    .io_mmio_ar_bits_id         (peri_arid),
    .io_mmio_ar_bits_user       (),
    .io_mmio_ar_bits_len        (peri_arlen),
    .io_mmio_ar_bits_size       (peri_arsize),
    .io_mmio_ar_bits_burst      (peri_arburst),
    .io_mmio_ar_bits_lock       (peri_arlock),
    .io_mmio_ar_bits_cache      (peri_arcache),
    .io_mmio_ar_bits_qos        (peri_arqos),

    .io_mmio_r_ready            (peri_rready),
    .io_mmio_r_valid            (peri_rvalid),
    .io_mmio_r_bits_resp        (peri_rresp),
    .io_mmio_r_bits_data        (peri_rdata),
    .io_mmio_r_bits_last        (peri_rlast),
    .io_mmio_r_bits_id          (peri_rid),
    .io_mmio_r_bits_user        (1'b0),

    // AXI4 DMA / FRONTEND
    .io_frontend_aw_ready       (dma_core_awready),
    .io_frontend_aw_valid       (dma_core_awvalid),
    .io_frontend_aw_bits_addr   (dma_core_awaddr[31:0]),
    .io_frontend_aw_bits_prot   (dma_core_awprot),
    .io_frontend_aw_bits_id     (dma_core_awid),
    .io_frontend_aw_bits_user   (1'b0),
    .io_frontend_aw_bits_len    (dma_core_awlen),
    .io_frontend_aw_bits_size   (dma_core_awsize),
    .io_frontend_aw_bits_burst  (dma_core_awburst),
    .io_frontend_aw_bits_lock   (dma_core_awlock),
    .io_frontend_aw_bits_cache  (dma_core_awcache),
    .io_frontend_aw_bits_qos    (dma_core_awqos),

    .io_frontend_w_ready        (dma_core_wready),
    .io_frontend_w_valid        (dma_core_wvalid),
    .io_frontend_w_bits_data    (dma_core_wdata[63:0]),
    .io_frontend_w_bits_strb    (dma_core_wstrb[7:0]),
    .io_frontend_w_bits_last    (dma_core_wlast),

    .io_frontend_b_ready        (dma_core_bready),
    .io_frontend_b_valid        (dma_core_bvalid),
    .io_frontend_b_bits_resp    (dma_core_bresp),
    .io_frontend_b_bits_id      (dma_core_bid),
    .io_frontend_b_bits_user    (),

    .io_frontend_ar_ready       (dma_core_arready),
    .io_frontend_ar_valid       (dma_core_arvalid),
    .io_frontend_ar_bits_addr   (dma_core_araddr[31:0]),
    .io_frontend_ar_bits_prot   (dma_core_arprot),
    .io_frontend_ar_bits_id     (dma_core_arid),
    .io_frontend_ar_bits_user   (1'b0),
    .io_frontend_ar_bits_len    (dma_core_arlen),
    .io_frontend_ar_bits_size   (dma_core_arsize),
    .io_frontend_ar_bits_burst  (dma_core_arburst),
    .io_frontend_ar_bits_lock   (dma_core_arlock),
    .io_frontend_ar_bits_cache  (dma_core_arcache),
    .io_frontend_ar_bits_qos    (dma_core_arqos),

    .io_frontend_r_ready        (dma_core_rready),
    .io_frontend_r_valid        (dma_core_rvalid),
    .io_frontend_r_bits_resp    (dma_core_rresp),
    .io_frontend_r_bits_data    (dma_core_rdata[63:0]),
    .io_frontend_r_bits_last    (dma_core_rlast),
    .io_frontend_r_bits_id      (dma_core_rid),
    .io_frontend_r_bits_user    (),

    // MIP
    .io_meip                    (io_extIntrs[1:0]),

    // difftest
    .difftest_ref_clock              (difftest_ref_clock),
    .difftest_ref_reset              (difftest_ref_reset),
    .difftest_pcie_clock             (difftest_pcie_clock),
    .difftest_to_host_axis_tready    (difftest_to_host_axis_tready),
    .difftest_to_host_axis_tvalid    (difftest_to_host_axis_tvalid),
    .difftest_to_host_axis_tdata     (difftest_to_host_axis_tdata),
    .difftest_to_host_axis_tkeep     (difftest_to_host_axis_tkeep),
    .difftest_to_host_axis_tlast     (difftest_to_host_axis_tlast),
    .difftest_from_host_axis_tready  (difftest_from_host_axis_tready),
    .difftest_from_host_axis_tvalid  (difftest_from_host_axis_tvalid),
    .difftest_from_host_axis_tdata   (difftest_from_host_axis_tdata),
    .difftest_from_host_axis_tkeep   (difftest_from_host_axis_tkeep),
    .difftest_from_host_axis_tlast   (difftest_from_host_axis_tlast),
    .difftest_clock_enable           (difftest_clock_enable),
    .difftest_hostCtrl_reset         (difftest_hostCtrl_reset),
    .difftest_hostCtrl_diffEnable    (difftest_hostCtrl_diffEnable),
    .difftest_hostCtrl_ilaTrigger    (difftest_hostCtrl_ilaTrigger),
    .difftest_hostCtrl_enableSquash   (difftest_hostCtrl_enableSquash),
    .difftest_cfg_axilite_awready    (difftest_cfg_axilite_awready),
    .difftest_cfg_axilite_awvalid    (difftest_cfg_axilite_awvalid),
    .difftest_cfg_axilite_awaddr     (difftest_cfg_axilite_awaddr),
    .difftest_cfg_axilite_wready     (difftest_cfg_axilite_wready),
    .difftest_cfg_axilite_wvalid     (difftest_cfg_axilite_wvalid),
    .difftest_cfg_axilite_wdata      (difftest_cfg_axilite_wdata),
    .difftest_cfg_axilite_wstrb      (difftest_cfg_axilite_wstrb),
    .difftest_cfg_axilite_bready     (difftest_cfg_axilite_bready),
    .difftest_cfg_axilite_bvalid     (difftest_cfg_axilite_bvalid),
    .difftest_cfg_axilite_bresp      (difftest_cfg_axilite_bresp),
    .difftest_cfg_axilite_arready    (difftest_cfg_axilite_arready),
    .difftest_cfg_axilite_arvalid    (difftest_cfg_axilite_arvalid),
    .difftest_cfg_axilite_araddr     (difftest_cfg_axilite_araddr),
    .difftest_cfg_axilite_rready     (difftest_cfg_axilite_rready),
    .difftest_cfg_axilite_rvalid     (difftest_cfg_axilite_rvalid),
    .difftest_cfg_axilite_rdata      (difftest_cfg_axilite_rdata),
    .difftest_cfg_axilite_rresp      (difftest_cfg_axilite_rresp)
);
endmodule
