#!/usr/bin/env bash
set -euo pipefail

[[ $# == 7 ]] || {
  echo "Usage: $0 ORIGIN_DIR WORK_DIR CORE_DIR JOBS FORCE DDR_SOURCE DDR_WIDTH" >&2
  exit 64
}
: "${UV_ROOT:?UV_ROOT is not set}"
: "${UV_XILINX_VIVADO:?UV_XILINX_VIVADO is not set}"

origin_dir=$1
work_dir=$2
core_dir=$3
jobs=$4
force=$5
ddr_source=$6
ddr_width=$7
script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)

require_file() {
  [[ -s $1 ]] || {
    echo "ERROR: required UVHS IP file is missing or empty: $1" >&2
    exit 1
  }
}

require_stub_port() {
  local stub=$1
  local pattern=$2
  local description=$3
  grep -Eq "$pattern" "$stub" || {
    echo "ERROR: generated IP stub has the wrong $description: $stub" >&2
    exit 1
  }
}

generalbus_stub_is_64() {
  grep -Eq 'output[[:space:]]+\[63:0\][[:space:]]*dut_axi_wdata' "$1" &&
    grep -Eq 'input[[:space:]]+\[63:0\][[:space:]]*dut_axi_rdata' "$1"
}

generalbus_stub_is_256() {
  grep -Eq 'output[[:space:]]+\[255:0\][[:space:]]*dut_axi_wdata' "$1" &&
    grep -Eq 'input[[:space:]]+\[255:0\][[:space:]]*dut_axi_rdata' "$1"
}

sanitize_generalbus_generator() {
  local generator=$1
  sed -i '/os[.]popen.*f_dcp_in.*f_dcp_out/c\    shutil.copy2(f_dcp_in, f_dcp_out)' \
    "$generator"
  sed -i 's|#!/bin/tcsh|#!/usr/bin/env bash|' "$generator"
  grep -Fq 'shutil.copy2(f_dcp_in, f_dcp_out)' "$generator"
  grep -Fq '#!/usr/bin/env bash' "$generator"
}

generate_generalbus() {
  local data_width=$1
  local gbus_source=$UV_ROOT/platform/U2.2/Prototype/ips/uvw_gbus.3.1
  local gbus_gen=$work_dir/ip-gen/generalbus_${data_width}
  local gbus_release=$gbus_gen/uvw_general_bus
  local width_check=generalbus_stub_is_${data_width}

  require_file "$gbus_source/gen_generalbus_ip.py"
  require_file "$gbus_source/uvw_axi3_generalbus.json"
  if [[ $force == 1 || ! -s $gbus_release/uvw_general_bus.dcp ||
        ! -s $gbus_release/uvw_general_bus_Stub.v ]] ||
      ! "$width_check" "$gbus_release/uvw_general_bus_Stub.v"; then
    rm -rf "$gbus_gen"
    mkdir -p "$gbus_gen"
    cp -a "$gbus_source" "$gbus_gen/ip-src"
    local generator=$gbus_gen/ip-src/gen_generalbus_ip.py
    sanitize_generalbus_generator "$generator"
    local json=$gbus_gen/uvw_axi3_generalbus.json
    cp -f "$gbus_source/uvw_axi3_generalbus.json" "$json"
    sed -i -E \
      "s|(\"IP_LOCATION\"[[:space:]]*:[[:space:]]*)\"[^\"]*\"|\1\"$gbus_gen/ip-src\"|; \
       s|(\"DATA_WIDTH\"[[:space:]]*:[[:space:]]*)\"[^\"]*\"|\1\"$data_width\"|" "$json"
    (cd "$gbus_gen" && PATH="$UV_XILINX_VIVADO/bin:$PATH" \
      python3 "$generator" -j "$json")
  fi
  require_file "$gbus_release/uvw_general_bus.dcp"
  require_file "$gbus_release/uvw_general_bus_Stub.v"
  "$width_check" "$gbus_release/uvw_general_bus_Stub.v"
  rm -rf "$work_dir/rtl/soc/uvw_general_bus"
  mkdir -p "$work_dir/rtl/soc" "$work_dir/rtl/stubs"
  cp -a "$gbus_release" "$work_dir/rtl/soc/uvw_general_bus"
  cp -f "$gbus_release/uvw_general_bus_Stub.v" \
    "$work_dir/rtl/soc/uvw_general_bus/uvw_general_bus_Stub.v"
  cp -f "$gbus_release/uvw_general_bus_Stub.v" "$work_dir/rtl/stubs/uvw_general_bus.v"
  echo "INFO: prepared ${data_width}-bit UVHS generalBus DCP"
}

prepare_generalbd() {
  local vendor_gbd=$UV_ROOT/platform/U2.2/Prototype/ips/gbd/generalBD
  local vendor_dcp=$vendor_gbd/generalBD.dcp
  local vendor_stub=$vendor_gbd/output/generalBD_stub.v
  local prepare_ip_py=$UV_ROOT/etc/auxtools/prepare_ip/prepare_ip.py
  local gbd_gen=$work_dir/ip-gen/generalbd
  local gbd_release=$gbd_gen/generalBD

  require_file "$vendor_dcp"
  require_file "$prepare_ip_py"
  require_file "$vendor_gbd/script/generalBD.json"
  if [[ $force == 1 || ! -s $gbd_release/generalBD.dcp ||
        ! -s $gbd_release/generalBD_Stub.v ]]; then
    rm -rf "$gbd_gen"
    mkdir -p "$gbd_gen/output"
    if [[ ! -s $vendor_stub ]]; then
      echo "INFO: regenerating GeneralBD synth stub from vendor DCP"
      cat >"$gbd_gen/write_stub.tcl" <<'TCL'
set dcp [lindex $argv 0]
set stub [lindex $argv 1]
open_checkpoint $dcp
file mkdir [file dirname $stub]
write_verilog -force -mode synth_stub $stub
close_design
TCL
      "$UV_XILINX_VIVADO/bin/vivado" -mode batch -nojournal -nolog \
        -source "$gbd_gen/write_stub.tcl" \
        -tclargs "$vendor_dcp" "$gbd_gen/output/generalBD_stub.v"
      vendor_stub=$gbd_gen/output/generalBD_stub.v
    else
      cp -f "$vendor_stub" "$gbd_gen/output/generalBD_stub.v"
      vendor_stub=$gbd_gen/output/generalBD_stub.v
    fi
    require_file "$vendor_stub"
    cp -f "$vendor_dcp" "$gbd_gen/output/generalBD.dcp"
    if [[ -f $vendor_gbd/output/generalBD_resource.v ]]; then
      cp -f "$vendor_gbd/output/generalBD_resource.v" \
        "$gbd_gen/output/generalBD_resource.v"
    else
      printf '* Empty resource file generated by UVHS GBus prepare_ip\n' \
        >"$gbd_gen/output/generalBD_resource.v"
    fi
    python3 - "$vendor_gbd/script/generalBD.json" "$gbd_gen" <<'PY'
import json, pathlib, sys
src, dst = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
data = json.loads(src.read_text())
data["RESOURCE_FILE"] = str(dst / "output/generalBD_resource.v")
data["STUB_FILE"] = str(dst / "output/generalBD_stub.v")
data["DCP_FILE"] = str(dst / "output/generalBD.dcp")
(dst / "generalBD.json").write_text(json.dumps(data, indent=2) + "\n")
PY
    (cd "$gbd_gen" && python3 "$prepare_ip_py" -j "$gbd_gen/generalBD.json" \
      -p U2 --gbd --nolib)
  fi
  require_file "$gbd_release/generalBD.dcp"
  require_file "$gbd_release/generalBD_Stub.v"
  require_stub_port "$gbd_release/generalBD_Stub.v" \
    'input[[:space:]]+\[255:0\][[:space:]]*gbd_sysbus_i' \
    'GeneralBD sysbus width; expected 256 bits'
  mkdir -p "$work_dir/rtl/soc" "$work_dir/rtl/stubs"
  cp -f "$gbd_release/generalBD.dcp" "$work_dir/rtl/soc/generalBD.dcp"
  cp -f "$gbd_release/generalBD_Stub.v" "$work_dir/rtl/stubs/generalBD.v"
  echo "INFO: prepared UVHS GeneralBD DCP from vendor IP"
}

# Export the Vivado IP owned by this repository.
vivado=$UV_XILINX_VIVADO/bin/vivado
vivado_args=(
  --origin_dir "$origin_dir" --out_dir "$work_dir"
  --core_dir "$core_dir" --jobs "$jobs"
  --hostif "${DIFFTEST_HOSTIF:-XDMA}"
)
[[ $force != 1 ]] || vivado_args+=(--force)
export VIVADO_HOME=$UV_XILINX_VIVADO XILINX_VIVADO=$UV_XILINX_VIVADO
"$vivado" -mode batch -source "$script_dir/export_vivado_ip.tcl" \
  -tclargs "${vivado_args[@]}"

hostif=${DIFFTEST_HOSTIF:-XDMA}
if [[ $hostif == GBUS ]]; then
  generate_generalbus 256
  prepare_generalbd
else
  # XDMA still needs the 64-bit vendor generalBus used by the existing UVHS
  # flash/runtime path. Generate it locally instead of checking in a DCP.
  generate_generalbus 64
fi

# Import the externally generated DDR DCP using its canonical work-tree names.
[[ $ddr_width == 64 || $ddr_width == 256 ]] || {
  echo "ERROR: unsupported UVHS DDR AXI width: $ddr_width" >&2
  exit 1
}
ddr_files=(
  rtl/soc/uvw_axi4_to_ddr4.dcp rtl/soc/uvw_axi4_to_ddr4_Stub.v
  script/uvw_axi4_to_ddr4_pblock.tcl script/custom_parts_ddr4_KSM26SES8_2666.csv
)
for rel in "${ddr_files[@]}"; do
  base=${rel##*/}
  destination=$work_dir/$rel
  source_file=
  for candidate in "$ddr_source/$rel" "$ddr_source/$base"; do
    [[ ! -f $candidate ]] || { source_file=$candidate; break; }
  done
  [[ -n $source_file ]] || source_file=$(find "$ddr_source" -type f -name "$base" -size +0c -print -quit)
  [[ -z $source_file ]] || { mkdir -p "$(dirname "$destination")"; cp -f "$source_file" "$destination"; }
done
for rel in "${ddr_files[@]:0:3}"; do require_file "$work_dir/$rel"; done
ddr_stub=$work_dir/rtl/soc/uvw_axi4_to_ddr4_Stub.v
if gzip -t "$ddr_stub" 2>/dev/null; then
  gzip -dc "$ddr_stub" >"$ddr_stub.decompressed"
  mv -f "$ddr_stub.decompressed" "$ddr_stub"
fi
last_bit=$((ddr_width - 1))
grep -Eq "input[[:space:]]+\[$last_bit:0\][[:space:]]*ddr4ip_dut_axi_wdata" "$ddr_stub"
grep -Eq "output[[:space:]]+\[$last_bit:0\][[:space:]]*ddr4ip_dut_axi_rdata" "$ddr_stub"
echo "INFO: verified UVHS DDR DCP AXI data width: $ddr_width"
