########################################################################
# Run synthesis and emit an incremental-synthesis reference checkpoint.
#
# Usage:
#   vivado -mode batch -source env-scripts/fpga_diff/tools/cpu_dcp_split/run_incremental_synth_checkpoint.tcl \
#     -tclargs <project.xpr> <out.dcp> [synth-run] [jobs]
#
# Older Vivado releases require write_checkpoint -incremental_synth to run in
# the same Vivado session that executed synth_design. Vivado 2024.1 exposes the
# synthesis INCREMENTAL_CHECKPOINT run property but rejects the
# -incremental_synth option at runtime, so the hook falls back to a normal
# synthesized DCP. That normal DCP is still accepted by the project-mode
# incremental synthesis run property in 2024.1.
########################################################################

proc usage {} {
  puts stderr "USAGE: vivado -mode batch -source env-scripts/fpga_diff/tools/cpu_dcp_split/run_incremental_synth_checkpoint.tcl -tclargs <project.xpr> <out.dcp> ?synth-run? ?jobs?"
}

source [file join [file dirname [info script]] vivado_common.tcl]

if {[llength $::argv] < 2 || [llength $::argv] > 4} {
  usage
  exit 2
}

set proj_path [file normalize [lindex $::argv 0]]
set out_dcp [file normalize [lindex $::argv 1]]
set synth_run_name "synth_1"
if {[llength $::argv] >= 3 && [string trim [lindex $::argv 2]] ne ""} {
  set synth_run_name [string trim [lindex $::argv 2]]
}
set jobs_arg ""
if {[llength $::argv] >= 4 && [string trim [lindex $::argv 3]] ne ""} {
  set jobs_arg [string trim [lindex $::argv 3]]
}

flow_require_file $proj_path "project"
flow_require_positive_int $jobs_arg "jobs"
set jobs [flow_default_jobs $jobs_arg 1]

file mkdir [file dirname $out_dcp]
set hook_dir [file normalize [file join [file dirname $out_dcp] hooks]]
file mkdir $hook_dir
set hook_path [file join $hook_dir "write_incremental_synth_checkpoint.post.tcl"]

set hook [open $hook_path w]
puts $hook "# Auto-generated by run_incremental_synth_checkpoint.tcl"
puts $hook [list set out_dcp $out_dcp]
puts $hook {file mkdir [file dirname $out_dcp]}
puts $hook {puts "INFO: Writing baseline synthesis checkpoint for incremental synthesis: $out_dcp"}
puts $hook {set_param constraints.enableBinaryConstraints false}
puts $hook [list source [file join [file dirname [info script]] vivado_common.tcl]]
puts $hook {set mode [flow_write_checkpoint_with_mode $out_dcp incremental_synth]}
puts $hook {puts "INFO: Wrote baseline synthesis checkpoint for incremental synthesis: $out_dcp (mode=$mode)"}
close $hook

puts "INFO: Opening project: $proj_path"
open_project $proj_path

set synth_obj [get_runs -quiet $synth_run_name]
if {[llength $synth_obj] == 0} {
  puts stderr "ERROR: synthesis run not found: $synth_run_name"
  exit 1
}
set synth_obj [lindex $synth_obj 0]

puts "INFO: Installing synthesis post-hook: $hook_path"
set post_hook_ok [flow_set_optional_property STEPS.SYNTH_DESIGN.TCL.POST $hook_path $synth_obj]
set write_inc_prop_ok [flow_set_optional_property WRITE_INCREMENTAL_SYNTH_CHECKPOINT 1 $synth_obj]
if {!$post_hook_ok} {
  puts stderr "ERROR: could not install synthesis post-hook on $synth_run_name"
  exit 1
}

set setup_path [file normalize [file join [file dirname $out_dcp] baseline_incremental_synth_setup.txt]]
set setup [open $setup_path w]
puts $setup "project=$proj_path"
puts $setup "synth_run=$synth_run_name"
puts $setup "out_dcp=$out_dcp"
puts $setup "post_hook=$hook_path"
puts $setup "post_hook_property_set=$post_hook_ok"
puts $setup "write_incremental_synth_checkpoint_property_set=$write_inc_prop_ok"
puts $setup "jobs=$jobs"
close $setup

puts "INFO: Resetting synthesis run: $synth_run_name"
reset_run $synth_obj
puts "INFO: Launching $synth_run_name with -jobs $jobs"
launch_runs $synth_obj -jobs $jobs
wait_on_run $synth_obj

set status [get_property STATUS $synth_obj]
puts "INFO: $synth_run_name status: $status"
if {![string match "*Complete*" $status]} {
  puts stderr "ERROR: synthesis did not complete"
  exit 1
}
if {![file exists $out_dcp]} {
  puts stderr "ERROR: incremental synthesis checkpoint was not created: $out_dcp"
  exit 1
}
if {[file size $out_dcp] <= 0} {
  puts stderr "ERROR: incremental synthesis checkpoint is empty: $out_dcp"
  exit 1
}

set mode_file [file rootname $out_dcp].mode
set checkpoint_mode "unknown"
if {[file exists $mode_file]} {
  set mode_fh [open $mode_file r]
  set mode_text [read $mode_fh]
  close $mode_fh
  if {[regexp {checkpoint_mode=([^\r\n]+)} $mode_text _ parsed_mode]} {
    set checkpoint_mode $parsed_mode
  }
}

puts "INFO: Synthesis checkpoint for incremental synthesis is ready: $out_dcp"
puts "INFO: checkpoint_mode=$checkpoint_mode"
