set cpu_files [list \
 [file normalize "${core_dir}/AcquireUnit.sv" ]\
 [file normalize "${core_dir}/Adder_18.sv" ]\
 [file normalize "${core_dir}/Adder_2.sv" ]\
 [file normalize "${core_dir}/Adder_chain_rnd.sv" ]\
 [file normalize "${core_dir}/Adder.sv" ]\
 [file normalize "${core_dir}/Adder_xb_20.sv" ]\
 [file normalize "${core_dir}/Adder_xb_3.sv" ]\
 [file normalize "${core_dir}/Adder_xb_8.sv" ]\
 [file normalize "${core_dir}/Adder_xb.sv" ]\
 [file normalize "${core_dir}/AddModule.sv" ]\
 [file normalize "${core_dir}/AddrAddModule.sv" ]\
 [file normalize "${core_dir}/AgeDetector_12.sv" ]\
 [file normalize "${core_dir}/AgeDetector_13.sv" ]\
 [file normalize "${core_dir}/AgeDetector_15.sv" ]\
 [file normalize "${core_dir}/AgeDetector_19.sv" ]\
 [file normalize "${core_dir}/AgeDetector_1.sv" ]\
 [file normalize "${core_dir}/AgeDetector_21.sv" ]\
 [file normalize "${core_dir}/AgeDetector_38.sv" ]\
 [file normalize "${core_dir}/AgeDetector_8.sv" ]\
 [file normalize "${core_dir}/AgeDetector_9.sv" ]\
 [file normalize "${core_dir}/AgeDetector.sv" ]\
 [file normalize "${core_dir}/AluDataModule.sv" ]\
 [file normalize "${core_dir}/AluResSel.sv" ]\
 [file normalize "${core_dir}/Alu.sv" ]\
 [file normalize "${core_dir}/AMOALU.sv" ]\
 [file normalize "${core_dir}/Arbiter1_InsUncacheResp.sv" ]\
 [file normalize "${core_dir}/Arbiter1_L1BankedDataWriteReqCtrl.sv" ]\
 [file normalize "${core_dir}/Arbiter1_L1BankedDataWriteReq.sv" ]\
 [file normalize "${core_dir}/Arbiter1_L2TLBImp_Anon.sv" ]\
 [file normalize "${core_dir}/Arbiter1_TagWriteReq.sv" ]\
 [file normalize "${core_dir}/Arbiter2_ICacheMissReq.sv" ]\
 [file normalize "${core_dir}/Arbiter2_L2TLBImp_Anon_1.sv" ]\
 [file normalize "${core_dir}/Arbiter2_L2TLBImp_Anon.sv" ]\
 [file normalize "${core_dir}/Arbiter2_L2TlbWithHptwIdBundle.sv" ]\
 [file normalize "${core_dir}/Arbiter2_L2ToL1Hint.sv" ]\
 [file normalize "${core_dir}/Arbiter2_LLPTW_Anon.sv" ]\
 [file normalize "${core_dir}/Arbiter2_MSHRRequest.sv" ]\
 [file normalize "${core_dir}/Arbiter2_PtwReq.sv" ]\
 [file normalize "${core_dir}/Arbiter2_StorePrefetchReq.sv" ]\
 [file normalize "${core_dir}/Arbiter3_1_Anon.sv" ]\
 [file normalize "${core_dir}/Arbiter3_L2TLBImp_Anon.sv" ]\
 [file normalize "${core_dir}/Arbiter3_L2TlbMemReqBundle.sv" ]\
 [file normalize "${core_dir}/Arbiter4_MainPipeReq.sv" ]\
 [file normalize "${core_dir}/Arbiter5_L2TlbWithHptwIdBundle.sv" ]\
 [file normalize "${core_dir}/Arbiter5_MSHRAcquire.sv" ]\
 [file normalize "${core_dir}/array_0_0_ext.v" ]\
 [file normalize "${core_dir}/array_0_0.sv" ]\
 [file normalize "${core_dir}/array_0_1_ext.v" ]\
 [file normalize "${core_dir}/array_0_1.sv" ]\
 [file normalize "${core_dir}/array_0_ext.v" ]\
 [file normalize "${core_dir}/array_0.sv" ]\
 [file normalize "${core_dir}/array_10_ext.v" ]\
 [file normalize "${core_dir}/array_10.sv" ]\
 [file normalize "${core_dir}/array_11_ext.v" ]\
 [file normalize "${core_dir}/array_11.sv" ]\
 [file normalize "${core_dir}/array_12_ext.v" ]\
 [file normalize "${core_dir}/array_12.sv" ]\
 [file normalize "${core_dir}/array_13_ext.v" ]\
 [file normalize "${core_dir}/array_13.sv" ]\
 [file normalize "${core_dir}/array_14_ext.v" ]\
 [file normalize "${core_dir}/array_14.sv" ]\
 [file normalize "${core_dir}/array_15_ext.v" ]\
 [file normalize "${core_dir}/array_15.sv" ]\
 [file normalize "${core_dir}/array_16_ext.v" ]\
 [file normalize "${core_dir}/array_16.sv" ]\
 [file normalize "${core_dir}/array_17_ext.v" ]\
 [file normalize "${core_dir}/array_17.sv" ]\
 [file normalize "${core_dir}/array_18_ext.v" ]\
 [file normalize "${core_dir}/array_18.sv" ]\
 [file normalize "${core_dir}/array_19_ext.v" ]\
 [file normalize "${core_dir}/array_19.sv" ]\
 [file normalize "${core_dir}/array_1_ext.v" ]\
 [file normalize "${core_dir}/array_1.sv" ]\
 [file normalize "${core_dir}/array_20_ext.v" ]\
 [file normalize "${core_dir}/array_20.sv" ]\
 [file normalize "${core_dir}/array_21_ext.v" ]\
 [file normalize "${core_dir}/array_21.sv" ]\
 [file normalize "${core_dir}/array_22.sv" ]\
 [file normalize "${core_dir}/array_2_ext.v" ]\
 [file normalize "${core_dir}/array_2.sv" ]\
 [file normalize "${core_dir}/array_3_ext.v" ]\
 [file normalize "${core_dir}/array_3.sv" ]\
 [file normalize "${core_dir}/array_4_ext.v" ]\
 [file normalize "${core_dir}/array_4.sv" ]\
 [file normalize "${core_dir}/array_5_ext.v" ]\
 [file normalize "${core_dir}/array_5.sv" ]\
 [file normalize "${core_dir}/array_6_ext.v" ]\
 [file normalize "${core_dir}/array_6.sv" ]\
 [file normalize "${core_dir}/array_7_ext.v" ]\
 [file normalize "${core_dir}/array_7.sv" ]\
 [file normalize "${core_dir}/array_8_ext.v" ]\
 [file normalize "${core_dir}/array_8.sv" ]\
 [file normalize "${core_dir}/array_9_ext.v" ]\
 [file normalize "${core_dir}/array_9.sv" ]\
 [file normalize "${core_dir}/array_ext.v" ]\
 [file normalize "${core_dir}/ArrayMulDataModule.sv" ]\
 [file normalize "${core_dir}/array.sv" ]\
 [file normalize "${core_dir}/AsyncQueueSink_1.sv" ]\
 [file normalize "${core_dir}/AsyncQueueSink_2.sv" ]\
 [file normalize "${core_dir}/AsyncQueueSink.sv" ]\
 [file normalize "${core_dir}/AsyncQueueSource_1.sv" ]\
 [file normalize "${core_dir}/AsyncQueueSource_2.sv" ]\
 [file normalize "${core_dir}/AsyncQueueSource.sv" ]\
 [file normalize "${core_dir}/AsyncResetSynchronizerPrimitiveShiftReg_d3_i0.sv" ]\
 [file normalize "${core_dir}/AsyncResetSynchronizerShiftReg_w1_d3_i0.sv" ]\
 [file normalize "${core_dir}/AtomicsUnit.sv" ]\
 [file normalize "${core_dir}/AXI4Buffer_3.sv" ]\
 [file normalize "${core_dir}/AXI4Buffer_7.sv" ]\
 [file normalize "${core_dir}/AXI4Buffer.sv" ]\
 [file normalize "${core_dir}/AXI4Deinterleaver.sv" ]\
 [file normalize "${core_dir}/AXI4Fragmenter.sv" ]\
 [file normalize "${core_dir}/AXI4IdIndexer_1.sv" ]\
 [file normalize "${core_dir}/AXI4IdIndexer_2.sv" ]\
 [file normalize "${core_dir}/AXI4IdIndexer.sv" ]\
 [file normalize "${core_dir}/AXI4ToTL.sv" ]\
 [file normalize "${core_dir}/AXI4UserYanker_1.sv" ]\
 [file normalize "${core_dir}/AXI4UserYanker_2.sv" ]\
 [file normalize "${core_dir}/AXI4UserYanker_3.sv" ]\
 [file normalize "${core_dir}/AXI4UserYanker.sv" ]\
 [file normalize "${core_dir}/Backend.sv" ]\
 [file normalize "${core_dir}/BankBinder_1.sv" ]\
 [file normalize "${core_dir}/BankBinder.sv" ]\
 [file normalize "${core_dir}/BankedDataArray.sv" ]\
 [file normalize "${core_dir}/BatchAssembler.sv" ]\
 [file normalize "${core_dir}/BatchCluster_10.sv" ]\
 [file normalize "${core_dir}/BatchCluster_11.sv" ]\
 [file normalize "${core_dir}/BatchCluster_12.sv" ]\
 [file normalize "${core_dir}/BatchCluster_13.sv" ]\
 [file normalize "${core_dir}/BatchCluster_14.sv" ]\
 [file normalize "${core_dir}/BatchCluster_15.sv" ]\
 [file normalize "${core_dir}/BatchCluster_16.sv" ]\
 [file normalize "${core_dir}/BatchCluster_17.sv" ]\
 [file normalize "${core_dir}/BatchCluster_18.sv" ]\
 [file normalize "${core_dir}/BatchCluster_19.sv" ]\
 [file normalize "${core_dir}/BatchCluster_1.sv" ]\
 [file normalize "${core_dir}/BatchCluster_20.sv" ]\
 [file normalize "${core_dir}/BatchCluster_21.sv" ]\
 [file normalize "${core_dir}/BatchCluster_22.sv" ]\
 [file normalize "${core_dir}/BatchCluster_23.sv" ]\
 [file normalize "${core_dir}/BatchCluster_24.sv" ]\
 [file normalize "${core_dir}/BatchCluster_25.sv" ]\
 [file normalize "${core_dir}/BatchCluster_26.sv" ]\
 [file normalize "${core_dir}/BatchCluster_2.sv" ]\
 [file normalize "${core_dir}/BatchCluster_3.sv" ]\
 [file normalize "${core_dir}/BatchCluster_4.sv" ]\
 [file normalize "${core_dir}/BatchCluster_5.sv" ]\
 [file normalize "${core_dir}/BatchCluster_6.sv" ]\
 [file normalize "${core_dir}/BatchCluster_7.sv" ]\
 [file normalize "${core_dir}/BatchCluster_8.sv" ]\
 [file normalize "${core_dir}/BatchCluster_9.sv" ]\
 [file normalize "${core_dir}/BatchCluster.sv" ]\
 [file normalize "${core_dir}/BatchCollector.sv" ]\
 [file normalize "${core_dir}/BatchEndpoint.sv" ]\
 [file normalize "${core_dir}/Bku.sv" ]\
 [file normalize "${core_dir}/BlockCipherModule.sv" ]\
 [file normalize "${core_dir}/BloomFilter.sv" ]\
 [file normalize "${core_dir}/BoothEncoderF64F32F16_3.sv" ]\
 [file normalize "${core_dir}/BoothEncoderF64F32F16.sv" ]\
 [file normalize "${core_dir}/BranchModule.sv" ]\
 [file normalize "${core_dir}/BranchUnit.sv" ]\
 [file normalize "${core_dir}/buffer_4x117.sv" ]\
 [file normalize "${core_dir}/buffer_7x514.sv" ]\
 [file normalize "${core_dir}/BusErrorUnit.sv" ]\
 [file normalize "${core_dir}/BusyTable_1.sv" ]\
 [file normalize "${core_dir}/BusyTable_2.sv" ]\
 [file normalize "${core_dir}/BusyTable_3.sv" ]\
 [file normalize "${core_dir}/BusyTable.sv" ]\
 [file normalize "${core_dir}/BypassNetwork.sv" ]\
 [file normalize "${core_dir}/ByteMaskTailGen.sv" ]\
 [file normalize "${core_dir}/C22.sv" ]\
 [file normalize "${core_dir}/C32.sv" ]\
 [file normalize "${core_dir}/C53.sv" ]\
 [file normalize "${core_dir}/CaptureChain.sv" ]\
 [file normalize "${core_dir}/CaptureUpdateChain_1.sv" ]\
 [file normalize "${core_dir}/CaptureUpdateChain_2.sv" ]\
 [file normalize "${core_dir}/CaptureUpdateChain.sv" ]\
 [file normalize "${core_dir}/CLINT.sv" ]\
 [file normalize "${core_dir}/ClmulModule.sv" ]\
 [file normalize "${core_dir}/ClockCrossingReg_w15.sv" ]\
 [file normalize "${core_dir}/ClockCrossingReg_w44.sv" ]\
 [file normalize "${core_dir}/ClockCrossingReg_w56.sv" ]\
 [file normalize "${core_dir}/ClockGate.sv" ]\
 [file normalize "${core_dir}/ClosePathAdder_2.sv" ]\
 [file normalize "${core_dir}/ClosePathAdderF16Pipeline_2.sv" ]\
 [file normalize "${core_dir}/ClosePathAdderF16Pipeline.sv" ]\
 [file normalize "${core_dir}/ClosePathAdder.sv" ]\
 [file normalize "${core_dir}/ClosePathF16Pipeline.sv" ]\
 [file normalize "${core_dir}/ClosePathF32WidenF16MixedPipelineAdder_2.sv" ]\
 [file normalize "${core_dir}/ClosePathF32WidenF16MixedPipelineAdder.sv" ]\
 [file normalize "${core_dir}/ClosePathF32WidenF16MixedPipeline.sv" ]\
 [file normalize "${core_dir}/ClosePathFloatAdderF64WidenPipeline.sv" ]\
 [file normalize "${core_dir}/CloseShiftLeftWithMux_1.sv" ]\
 [file normalize "${core_dir}/CloseShiftLeftWithMux_9.sv" ]\
 [file normalize "${core_dir}/CloseShiftLeftWithMux.sv" ]\
 [file normalize "${core_dir}/CLZ_11.sv" ]\
 [file normalize "${core_dir}/CLZ_28.sv" ]\
 [file normalize "${core_dir}/CLZ_29.sv" ]\
 [file normalize "${core_dir}/CLZ_30.sv" ]\
 [file normalize "${core_dir}/CLZ_31.sv" ]\
 [file normalize "${core_dir}/CLZ_6.sv" ]\
 [file normalize "${core_dir}/CLZ_7.sv" ]\
 [file normalize "${core_dir}/CLZ_9.sv" ]\
 [file normalize "${core_dir}/CLZ.sv" ]\
 [file normalize "${core_dir}/CMOUnit.sv" ]\
 [file normalize "${core_dir}/CommitIDModule.sv" ]\
 [file normalize "${core_dir}/compare_2to1_2.sv" ]\
 [file normalize "${core_dir}/compare_2to1.sv" ]\
 [file normalize "${core_dir}/compare_3to1_1.sv" ]\
 [file normalize "${core_dir}/compare_3to1_2.sv" ]\
 [file normalize "${core_dir}/compare_3to1_6.sv" ]\
 [file normalize "${core_dir}/compare_3to1.sv" ]\
 [file normalize "${core_dir}/Composer.sv" ]\
 [file normalize "${core_dir}/CompressUnit.sv" ]\
 [file normalize "${core_dir}/ConditionalZeroModule.sv" ]\
 [file normalize "${core_dir}/Conversion_12.sv" ]\
 [file normalize "${core_dir}/Conversion_8.sv" ]\
 [file normalize "${core_dir}/Conversion.sv" ]\
 [file normalize "${core_dir}/CounterFilter.sv" ]\
 [file normalize "${core_dir}/CountModule.sv" ]\
 [file normalize "${core_dir}/CryptoModule.sv" ]\
 [file normalize "${core_dir}/CSA3_2_3956.sv" ]\
 [file normalize "${core_dir}/CSA3_2_3960.sv" ]\
 [file normalize "${core_dir}/CSA3_2_3962.sv" ]\
 [file normalize "${core_dir}/CSA3_2_3987.sv" ]\
 [file normalize "${core_dir}/CSA3_2_3988.sv" ]\
 [file normalize "${core_dir}/CSA3_2_3992.sv" ]\
 [file normalize "${core_dir}/CSA3_2_4017.sv" ]\
 [file normalize "${core_dir}/CSA3_2_4111.sv" ]\
 [file normalize "${core_dir}/CSA3_2_4173.sv" ]\
 [file normalize "${core_dir}/CSA3_2.sv" ]\
 [file normalize "${core_dir}/CSA3to2_124.sv" ]\
 [file normalize "${core_dir}/CSA3to2_125.sv" ]\
 [file normalize "${core_dir}/CSA3to2_127.sv" ]\
 [file normalize "${core_dir}/CSA3to2_132.sv" ]\
 [file normalize "${core_dir}/CSA3to2_20.sv" ]\
 [file normalize "${core_dir}/CSA3to2_24.sv" ]\
 [file normalize "${core_dir}/CSA3to2.sv" ]\
 [file normalize "${core_dir}/CSA4to2_15.sv" ]\
 [file normalize "${core_dir}/CSA4to2_16.sv" ]\
 [file normalize "${core_dir}/CSA4to2.sv" ]\
 [file normalize "${core_dir}/CSA_Nto2With3to2MainPipeline.sv" ]\
 [file normalize "${core_dir}/CSRPermitModule.sv" ]\
 [file normalize "${core_dir}/CSR.sv" ]\
 [file normalize "${core_dir}/CtrlBlock.sv" ]\
 [file normalize "${core_dir}/CtrlUnit.sv" ]\
 [file normalize "${core_dir}/CustomL1Hint.sv" ]\
 [file normalize "${core_dir}/CVT16.sv" ]\
 [file normalize "${core_dir}/CVT32.sv" ]\
 [file normalize "${core_dir}/CVT64_1.sv" ]\
 [file normalize "${core_dir}/CVT64.sv" ]\
 [file normalize "${core_dir}/cycleModule.sv" ]\
 [file normalize "${core_dir}/data_mem_0_4x2.sv" ]\
 [file normalize "${core_dir}/data_mem_0_8x3.sv" ]\
 [file normalize "${core_dir}/data_mem_16x12.sv" ]\
 [file normalize "${core_dir}/data_mem_8x4.sv" ]\
 [file normalize "${core_dir}/DataModule__16entry.sv" ]\
 [file normalize "${core_dir}/DataModule__8entry_1.sv" ]\
 [file normalize "${core_dir}/DataModule__8entry_2.sv" ]\
 [file normalize "${core_dir}/DataModule__8entry_3.sv" ]\
 [file normalize "${core_dir}/DataModule__8entry.sv" ]\
 [file normalize "${core_dir}/DataModule_BackendPC_8entry.sv" ]\
 [file normalize "${core_dir}/DataModule_FtqPC_8entry.sv" ]\
 [file normalize "${core_dir}/DatamoduleResultBuffer_1.sv" ]\
 [file normalize "${core_dir}/DatamoduleResultBuffer.sv" ]\
 [file normalize "${core_dir}/DataPath.sv" ]\
 [file normalize "${core_dir}/DataSel.sv" ]\
 [file normalize "${core_dir}/DataSRAMBank.sv" ]\
 [file normalize "${core_dir}/DataStorage_2.sv" ]\
 [file normalize "${core_dir}/DataStorage.sv" ]\
 [file normalize "${core_dir}/DCache.sv" ]\
 [file normalize "${core_dir}/DCacheWrapper.sv" ]\
 [file normalize "${core_dir}/DcsrModule.sv" ]\
 [file normalize "${core_dir}/DebugModule.sv" ]\
 [file normalize "${core_dir}/Debug.sv" ]\
 [file normalize "${core_dir}/DebugTransportModuleJTAG.sv" ]\
 [file normalize "${core_dir}/DecodeStage.sv" ]\
 [file normalize "${core_dir}/DecodeUnitComp.sv" ]\
 [file normalize "${core_dir}/DecodeUnit.sv" ]\
 [file normalize "${core_dir}/DelayN_13.sv" ]\
 [file normalize "${core_dir}/DelayN_15.sv" ]\
 [file normalize "${core_dir}/DelayN_1.sv" ]\
 [file normalize "${core_dir}/DelayN_208.sv" ]\
 [file normalize "${core_dir}/DelayN_214.sv" ]\
 [file normalize "${core_dir}/DelayN_215.sv" ]\
 [file normalize "${core_dir}/DelayN_216.sv" ]\
 [file normalize "${core_dir}/DelayN_219.sv" ]\
 [file normalize "${core_dir}/DelayN_220.sv" ]\
 [file normalize "${core_dir}/DelayN_258.sv" ]\
 [file normalize "${core_dir}/DelayN_280.sv" ]\
 [file normalize "${core_dir}/DelayN_282.sv" ]\
 [file normalize "${core_dir}/DelayN_7.sv" ]\
 [file normalize "${core_dir}/DelayN_8.sv" ]\
 [file normalize "${core_dir}/DelayN_9.sv" ]\
 [file normalize "${core_dir}/DelayN.sv" ]\
 [file normalize "${core_dir}/DelayNWithValid_103.sv" ]\
 [file normalize "${core_dir}/DelayNWithValid_104.sv" ]\
 [file normalize "${core_dir}/DelayNWithValid_1.sv" ]\
 [file normalize "${core_dir}/DelayNWithValid_27.sv" ]\
 [file normalize "${core_dir}/DelayNWithValid_2.sv" ]\
 [file normalize "${core_dir}/DelayNWithValid_30.sv" ]\
 [file normalize "${core_dir}/DelayNWithValid_3.sv" ]\
 [file normalize "${core_dir}/DelayNWithValid_6.sv" ]\
 [file normalize "${core_dir}/DelayNWithValid_75.sv" ]\
 [file normalize "${core_dir}/DelayNWithValid_76.sv" ]\
 [file normalize "${core_dir}/DelayNWithValid_82.sv" ]\
 [file normalize "${core_dir}/DelayNWithValid.sv" ]\
 [file normalize "${core_dir}/DelayReg_16.sv" ]\
 [file normalize "${core_dir}/DelayReg_18.sv" ]\
 [file normalize "${core_dir}/DelayReg_19.sv" ]\
 [file normalize "${core_dir}/DelayReg_20.sv" ]\
 [file normalize "${core_dir}/DelayReg_21.sv" ]\
 [file normalize "${core_dir}/DelayReg_22.sv" ]\
 [file normalize "${core_dir}/DelayReg_23.sv" ]\
 [file normalize "${core_dir}/DelayReg.sv" ]\
 [file normalize "${core_dir}/DeltaEndpoint.sv" ]\
 [file normalize "${core_dir}/DeMultiplexer_1.sv" ]\
 [file normalize "${core_dir}/DeMultiplexer.sv" ]\
 [file normalize "${core_dir}/DiffExtBatch.v" ]\
 [file normalize "${core_dir}/Directory_2.sv" ]\
 [file normalize "${core_dir}/Directory_Anon.sv" ]\
 [file normalize "${core_dir}/Directory.sv" ]\
 [file normalize "${core_dir}/Dispatcher_10.sv" ]\
 [file normalize "${core_dir}/Dispatcher_13.sv" ]\
 [file normalize "${core_dir}/Dispatcher_14.sv" ]\
 [file normalize "${core_dir}/Dispatcher_15.sv" ]\
 [file normalize "${core_dir}/Dispatcher_16.sv" ]\
 [file normalize "${core_dir}/Dispatcher_17.sv" ]\
 [file normalize "${core_dir}/Dispatcher_1.sv" ]\
 [file normalize "${core_dir}/Dispatcher_4.sv" ]\
 [file normalize "${core_dir}/Dispatcher_5.sv" ]\
 [file normalize "${core_dir}/Dispatcher_7.sv" ]\
 [file normalize "${core_dir}/Dispatcher_8.sv" ]\
 [file normalize "${core_dir}/Dispatcher_9.sv" ]\
 [file normalize "${core_dir}/Dispatcher.sv" ]\
 [file normalize "${core_dir}/DivUnit.sv" ]\
 [file normalize "${core_dir}/DMIToTL.sv" ]\
 [file normalize "${core_dir}/DpcModule.sv" ]\
 [file normalize "${core_dir}/DretEventModule.sv" ]\
 [file normalize "${core_dir}/Dscratch0Module.sv" ]\
 [file normalize "${core_dir}/Dscratch1Module.sv" ]\
 [file normalize "${core_dir}/dt_48x1.sv" ]\
 [file normalize "${core_dir}/dt_pcTransType_48x2.sv" ]\
 [file normalize "${core_dir}/DummyDPICBatchWrapper.sv" ]\
 [file normalize "${core_dir}/DuplicatedTagArray.sv" ]\
 [file normalize "${core_dir}/EnqEntry_10.sv" ]\
 [file normalize "${core_dir}/EnqEntry_12.sv" ]\
 [file normalize "${core_dir}/EnqEntry_14.sv" ]\
 [file normalize "${core_dir}/EnqEntry_16.sv" ]\
 [file normalize "${core_dir}/EnqEntry_18.sv" ]\
 [file normalize "${core_dir}/EnqEntry_20.sv" ]\
 [file normalize "${core_dir}/EnqEntry_24.sv" ]\
 [file normalize "${core_dir}/EnqEntry_30.sv" ]\
 [file normalize "${core_dir}/EnqEntry_4.sv" ]\
 [file normalize "${core_dir}/EnqEntry_6.sv" ]\
 [file normalize "${core_dir}/EnqEntry_8.sv" ]\
 [file normalize "${core_dir}/EnqEntry.sv" ]\
 [file normalize "${core_dir}/EnqEntryVecMem_2.sv" ]\
 [file normalize "${core_dir}/EnqEntryVecMem.sv" ]\
 [file normalize "${core_dir}/EnqPolicy_14.sv" ]\
 [file normalize "${core_dir}/EnqPolicy_8.sv" ]\
 [file normalize "${core_dir}/EnqPolicy.sv" ]\
 [file normalize "${core_dir}/EntriesAluBrhJmpI2fVsetriwiVsetriwvfI2v.sv" ]\
 [file normalize "${core_dir}/EntriesAluCsrFenceDiv.sv" ]\
 [file normalize "${core_dir}/EntriesAluMulBkuBrhJmp.sv" ]\
 [file normalize "${core_dir}/EntriesFaluFcvtF2vFmacFdiv.sv" ]\
 [file normalize "${core_dir}/EntriesFaluFmacFdiv.sv" ]\
 [file normalize "${core_dir}/EntriesFaluFmac.sv" ]\
 [file normalize "${core_dir}/EntriesLdu.sv" ]\
 [file normalize "${core_dir}/EntriesStaMou.sv" ]\
 [file normalize "${core_dir}/EntriesStdMoud.sv" ]\
 [file normalize "${core_dir}/EntriesVfdivVidiv.sv" ]\
 [file normalize "${core_dir}/EntriesVfmaVialuFixVfalu.sv" ]\
 [file normalize "${core_dir}/EntriesVfmaVialuFixVimacVppuVfaluVfcvtVipuVsetrvfwvf.sv" ]\
 [file normalize "${core_dir}/EntriesVlduVstu.sv" ]\
 [file normalize "${core_dir}/EntriesVlduVstuVseglduVsegstu.sv" ]\
 [file normalize "${core_dir}/Estimate7.sv" ]\
 [file normalize "${core_dir}/ExceptionGen.sv" ]\
 [file normalize "${core_dir}/ExeUnit_10.sv" ]\
 [file normalize "${core_dir}/ExeUnit_13.sv" ]\
 [file normalize "${core_dir}/ExeUnit_14.sv" ]\
 [file normalize "${core_dir}/ExeUnit_15.sv" ]\
 [file normalize "${core_dir}/ExeUnit_16.sv" ]\
 [file normalize "${core_dir}/ExeUnit_17.sv" ]\
 [file normalize "${core_dir}/ExeUnit_1.sv" ]\
 [file normalize "${core_dir}/ExeUnit_4.sv" ]\
 [file normalize "${core_dir}/ExeUnit_5.sv" ]\
 [file normalize "${core_dir}/ExeUnit_7.sv" ]\
 [file normalize "${core_dir}/ExeUnit_8.sv" ]\
 [file normalize "${core_dir}/ExeUnit_9.sv" ]\
 [file normalize "${core_dir}/ExeUnit.sv" ]\
 [file normalize "${core_dir}/extern_modules.sv" ]\
 [file normalize "${core_dir}/ExuBlock_1.sv" ]\
 [file normalize "${core_dir}/ExuBlock_2.sv" ]\
 [file normalize "${core_dir}/ExuBlock.sv" ]\
 [file normalize "${core_dir}/F3Predecoder.sv" ]\
 [file normalize "${core_dir}/FAlu.sv" ]\
 [file normalize "${core_dir}/FarPathAdderF16Pipeline.sv" ]\
 [file normalize "${core_dir}/FarPathAdderF64WidenPipeline.sv" ]\
 [file normalize "${core_dir}/FarPathF16Pipeline.sv" ]\
 [file normalize "${core_dir}/FarPathF32WidenF16MixedAdderPipeline.sv" ]\
 [file normalize "${core_dir}/FarPathF32WidenF16MixedPipeline.sv" ]\
 [file normalize "${core_dir}/FarPathFloatAdderF64WidenPipeline.sv" ]\
 [file normalize "${core_dir}/FarShiftRightWithMuxInvFirst_18.sv" ]\
 [file normalize "${core_dir}/FarShiftRightWithMuxInvFirst_2.sv" ]\
 [file normalize "${core_dir}/FarShiftRightWithMuxInvFirst.sv" ]\
 [file normalize "${core_dir}/FastArbiter_11.sv" ]\
 [file normalize "${core_dir}/FastArbiter_12.sv" ]\
 [file normalize "${core_dir}/FastArbiter_13.sv" ]\
 [file normalize "${core_dir}/FastArbiter_14.sv" ]\
 [file normalize "${core_dir}/FastArbiter_15.sv" ]\
 [file normalize "${core_dir}/FastArbiter_1.sv" ]\
 [file normalize "${core_dir}/FastArbiter_2.sv" ]\
 [file normalize "${core_dir}/FastArbiter_3.sv" ]\
 [file normalize "${core_dir}/FastArbiter_4.sv" ]\
 [file normalize "${core_dir}/FastArbiter_5.sv" ]\
 [file normalize "${core_dir}/FastArbiter.sv" ]\
 [file normalize "${core_dir}/FauFTB.sv" ]\
 [file normalize "${core_dir}/FauFTBWay.sv" ]\
 [file normalize "${core_dir}/FcsrModule.sv" ]\
 [file normalize "${core_dir}/FCVT.sv" ]\
 [file normalize "${core_dir}/FDivSqrt.sv" ]\
 [file normalize "${core_dir}/Fence.sv" ]\
 [file normalize "${core_dir}/FIFOReg.sv" ]\
 [file normalize "${core_dir}/FliDTable.sv" ]\
 [file normalize "${core_dir}/FliHTable.sv" ]\
 [file normalize "${core_dir}/FliSTable.sv" ]\
 [file normalize "${core_dir}/FloatAdderF16Pipeline.sv" ]\
 [file normalize "${core_dir}/FloatAdderF32F16MixedPipeline.sv" ]\
 [file normalize "${core_dir}/FloatAdderF32WidenF16MixedPipeline.sv" ]\
 [file normalize "${core_dir}/FloatAdderF64Pipeline.sv" ]\
 [file normalize "${core_dir}/FloatAdderF64WidenPipeline.sv" ]\
 [file normalize "${core_dir}/FloatAdder.sv" ]\
 [file normalize "${core_dir}/FloatAdderWidenFormat.sv" ]\
 [file normalize "${core_dir}/FloatDividerR64.sv" ]\
 [file normalize "${core_dir}/FloatDivider.sv" ]\
 [file normalize "${core_dir}/FloatFMA.sv" ]\
 [file normalize "${core_dir}/FMA.sv" ]\
 [file normalize "${core_dir}/FoldedSRAMTemplate_10.sv" ]\
 [file normalize "${core_dir}/FoldedSRAMTemplate_11.sv" ]\
 [file normalize "${core_dir}/FoldedSRAMTemplate_15.sv" ]\
 [file normalize "${core_dir}/FoldedSRAMTemplate_16.sv" ]\
 [file normalize "${core_dir}/FoldedSRAMTemplate_18.sv" ]\
 [file normalize "${core_dir}/FoldedSRAMTemplate_1.sv" ]\
 [file normalize "${core_dir}/FoldedSRAMTemplate.sv" ]\
 [file normalize "${core_dir}/FPCVT.sv" ]\
 [file normalize "${core_dir}/FPDecoder.sv" ]\
 [file normalize "${core_dir}/fpdiv_r64_block.sv" ]\
 [file normalize "${core_dir}/fpdiv_r64_block_vector.sv" ]\
 [file normalize "${core_dir}/FP_INCVT.sv" ]\
 [file normalize "${core_dir}/FpRegFilePart0.sv" ]\
 [file normalize "${core_dir}/FpRegFilePart1.sv" ]\
 [file normalize "${core_dir}/FpRegFilePart2.sv" ]\
 [file normalize "${core_dir}/FpRegFilePart3.sv" ]\
 [file normalize "${core_dir}/FpRFReadArbiter.sv" ]\
 [file normalize "${core_dir}/FpRFWBCollideChecker.sv" ]\
 [file normalize "${core_dir}/fpsqrt_r16_block.sv" ]\
 [file normalize "${core_dir}/fpsqrt_r16.sv" ]\
 [file normalize "${core_dir}/fpsqrt_vector_r16.sv" ]\
 [file normalize "${core_dir}/FreeList_1.sv" ]\
 [file normalize "${core_dir}/FreeList_3.sv" ]\
 [file normalize "${core_dir}/FreeList_4.sv" ]\
 [file normalize "${core_dir}/FreeList_5.sv" ]\
 [file normalize "${core_dir}/FreeList_6.sv" ]\
 [file normalize "${core_dir}/FreeList.sv" ]\
 [file normalize "${core_dir}/FrontendBridge.sv" ]\
 [file normalize "${core_dir}/Frontend.sv" ]\
 [file normalize "${core_dir}/FrontendTrigger.sv" ]\
 [file normalize "${core_dir}/FTBBank.sv" ]\
 [file normalize "${core_dir}/FTBEntryGen.sv" ]\
 [file normalize "${core_dir}/FTB.sv" ]\
 [file normalize "${core_dir}/FtqNRSRAM.sv" ]\
 [file normalize "${core_dir}/FtqPcMemWrapper.sv" ]\
 [file normalize "${core_dir}/Ftq.sv" ]\
 [file normalize "${core_dir}/FuBusyTableRead_105.sv" ]\
 [file normalize "${core_dir}/FuBusyTableRead_22.sv" ]\
 [file normalize "${core_dir}/FuBusyTableRead_23.sv" ]\
 [file normalize "${core_dir}/FuBusyTableRead_26.sv" ]\
 [file normalize "${core_dir}/FuBusyTableRead_28.sv" ]\
 [file normalize "${core_dir}/FuBusyTableRead_2.sv" ]\
 [file normalize "${core_dir}/FuBusyTableRead_32.sv" ]\
 [file normalize "${core_dir}/FuBusyTableRead_42.sv" ]\
 [file normalize "${core_dir}/FuBusyTableRead_43.sv" ]\
 [file normalize "${core_dir}/FuBusyTableRead_52.sv" ]\
 [file normalize "${core_dir}/FuBusyTableRead_53.sv" ]\
 [file normalize "${core_dir}/FuBusyTableRead_68.sv" ]\
 [file normalize "${core_dir}/FuBusyTableRead_69.sv" ]\
 [file normalize "${core_dir}/FuBusyTableRead_71.sv" ]\
 [file normalize "${core_dir}/FuBusyTableRead_73.sv" ]\
 [file normalize "${core_dir}/FuBusyTableRead_75.sv" ]\
 [file normalize "${core_dir}/FuBusyTableRead_79.sv" ]\
 [file normalize "${core_dir}/FuBusyTableRead_80.sv" ]\
 [file normalize "${core_dir}/FuBusyTableRead.sv" ]\
 [file normalize "${core_dir}/FuBusyTableWrite_105.sv" ]\
 [file normalize "${core_dir}/FuBusyTableWrite_117.sv" ]\
 [file normalize "${core_dir}/FuBusyTableWrite_22.sv" ]\
 [file normalize "${core_dir}/FuBusyTableWrite_23.sv" ]\
 [file normalize "${core_dir}/FuBusyTableWrite_24.sv" ]\
 [file normalize "${core_dir}/FuBusyTableWrite_26.sv" ]\
 [file normalize "${core_dir}/FuBusyTableWrite_28.sv" ]\
 [file normalize "${core_dir}/FuBusyTableWrite_2.sv" ]\
 [file normalize "${core_dir}/FuBusyTableWrite_32.sv" ]\
 [file normalize "${core_dir}/FuBusyTableWrite_3.sv" ]\
 [file normalize "${core_dir}/FuBusyTableWrite_42.sv" ]\
 [file normalize "${core_dir}/FuBusyTableWrite_43.sv" ]\
 [file normalize "${core_dir}/FuBusyTableWrite_46.sv" ]\
 [file normalize "${core_dir}/FuBusyTableWrite_52.sv" ]\
 [file normalize "${core_dir}/FuBusyTableWrite_53.sv" ]\
 [file normalize "${core_dir}/FuBusyTableWrite_68.sv" ]\
 [file normalize "${core_dir}/FuBusyTableWrite_69.sv" ]\
 [file normalize "${core_dir}/FuBusyTableWrite_71.sv" ]\
 [file normalize "${core_dir}/FuBusyTableWrite_73.sv" ]\
 [file normalize "${core_dir}/FuBusyTableWrite_75.sv" ]\
 [file normalize "${core_dir}/FuBusyTableWrite_79.sv" ]\
 [file normalize "${core_dir}/FuBusyTableWrite_80.sv" ]\
 [file normalize "${core_dir}/FuBusyTableWrite_95.sv" ]\
 [file normalize "${core_dir}/FuBusyTableWrite.sv" ]\
 [file normalize "${core_dir}/FusionDecoder.sv" ]\
 [file normalize "${core_dir}/GatedSplittedSRAM.sv" ]\
 [file normalize "${core_dir}/GatewayEndpoint.sv" ]\
 [file normalize "${core_dir}/GetE8OffsetInVreg.sv" ]\
 [file normalize "${core_dir}/GPAMem.sv" ]\
 [file normalize "${core_dir}/GrantBuffer.sv" ]\
 [file normalize "${core_dir}/HashModule.sv" ]\
 [file normalize "${core_dir}/HcounterenModule.sv" ]\
 [file normalize "${core_dir}/HedelegModule.sv" ]\
 [file normalize "${core_dir}/HenvcfgModule.sv" ]\
 [file normalize "${core_dir}/HgatpModule.sv" ]\
 [file normalize "${core_dir}/HgeieModule.sv" ]\
 [file normalize "${core_dir}/HgeipModule.sv" ]\
 [file normalize "${core_dir}/HidelegModule.sv" ]\
 [file normalize "${core_dir}/HieModule.sv" ]\
 [file normalize "${core_dir}/HipModule.sv" ]\
 [file normalize "${core_dir}/HPerfCounter_13.sv" ]\
 [file normalize "${core_dir}/HPerfCounter_21.sv" ]\
 [file normalize "${core_dir}/HPerfCounter_8.sv" ]\
 [file normalize "${core_dir}/HPerfCounter.sv" ]\
 [file normalize "${core_dir}/HPerfMonitor_1.sv" ]\
 [file normalize "${core_dir}/HPerfMonitor_2.sv" ]\
 [file normalize "${core_dir}/HPerfMonitor_3.sv" ]\
 [file normalize "${core_dir}/HPerfMonitor.sv" ]\
 [file normalize "${core_dir}/Hpmcounter10Module.sv" ]\
 [file normalize "${core_dir}/Hpmcounter11Module.sv" ]\
 [file normalize "${core_dir}/Hpmcounter12Module.sv" ]\
 [file normalize "${core_dir}/Hpmcounter13Module.sv" ]\
 [file normalize "${core_dir}/Hpmcounter14Module.sv" ]\
 [file normalize "${core_dir}/Hpmcounter15Module.sv" ]\
 [file normalize "${core_dir}/Hpmcounter16Module.sv" ]\
 [file normalize "${core_dir}/Hpmcounter17Module.sv" ]\
 [file normalize "${core_dir}/Hpmcounter18Module.sv" ]\
 [file normalize "${core_dir}/Hpmcounter19Module.sv" ]\
 [file normalize "${core_dir}/Hpmcounter20Module.sv" ]\
 [file normalize "${core_dir}/Hpmcounter21Module.sv" ]\
 [file normalize "${core_dir}/Hpmcounter22Module.sv" ]\
 [file normalize "${core_dir}/Hpmcounter23Module.sv" ]\
 [file normalize "${core_dir}/Hpmcounter24Module.sv" ]\
 [file normalize "${core_dir}/Hpmcounter25Module.sv" ]\
 [file normalize "${core_dir}/Hpmcounter26Module.sv" ]\
 [file normalize "${core_dir}/Hpmcounter27Module.sv" ]\
 [file normalize "${core_dir}/Hpmcounter28Module.sv" ]\
 [file normalize "${core_dir}/Hpmcounter29Module.sv" ]\
 [file normalize "${core_dir}/Hpmcounter30Module.sv" ]\
 [file normalize "${core_dir}/Hpmcounter31Module.sv" ]\
 [file normalize "${core_dir}/Hpmcounter3Module.sv" ]\
 [file normalize "${core_dir}/Hpmcounter4Module.sv" ]\
 [file normalize "${core_dir}/Hpmcounter5Module.sv" ]\
 [file normalize "${core_dir}/Hpmcounter6Module.sv" ]\
 [file normalize "${core_dir}/Hpmcounter7Module.sv" ]\
 [file normalize "${core_dir}/Hpmcounter8Module.sv" ]\
 [file normalize "${core_dir}/Hpmcounter9Module.sv" ]\
 [file normalize "${core_dir}/HPTW.sv" ]\
 [file normalize "${core_dir}/HstateenModule.sv" ]\
 [file normalize "${core_dir}/HstatusModule.sv" ]\
 [file normalize "${core_dir}/HtimedeltaModule.sv" ]\
 [file normalize "${core_dir}/HtinstModule.sv" ]\
 [file normalize "${core_dir}/HtvalModule.sv" ]\
 [file normalize "${core_dir}/HuanCun.sv" ]\
 [file normalize "${core_dir}/HvictlModule.sv" ]\
 [file normalize "${core_dir}/HvienModule.sv" ]\
 [file normalize "${core_dir}/HvipModule.sv" ]\
 [file normalize "${core_dir}/Hviprio1Module.sv" ]\
 [file normalize "${core_dir}/Hviprio2Module.sv" ]\
 [file normalize "${core_dir}/I8DivNr4.sv" ]\
 [file normalize "${core_dir}/IBuffer.sv" ]\
 [file normalize "${core_dir}/ICacheBuffer.sv" ]\
 [file normalize "${core_dir}/ICacheCtrlBuffer.sv" ]\
 [file normalize "${core_dir}/ICacheCtrlUnit.sv" ]\
 [file normalize "${core_dir}/ICacheDataArray.sv" ]\
 [file normalize "${core_dir}/ICacheMainPipe.sv" ]\
 [file normalize "${core_dir}/ICacheMetaArray.sv" ]\
 [file normalize "${core_dir}/ICacheMissUnit.sv" ]\
 [file normalize "${core_dir}/ICacheMSHR_10.sv" ]\
 [file normalize "${core_dir}/ICacheMSHR_11.sv" ]\
 [file normalize "${core_dir}/ICacheMSHR_12.sv" ]\
 [file normalize "${core_dir}/ICacheMSHR_13.sv" ]\
 [file normalize "${core_dir}/ICacheMSHR_1.sv" ]\
 [file normalize "${core_dir}/ICacheMSHR_2.sv" ]\
 [file normalize "${core_dir}/ICacheMSHR_3.sv" ]\
 [file normalize "${core_dir}/ICacheMSHR_4.sv" ]\
 [file normalize "${core_dir}/ICacheMSHR_5.sv" ]\
 [file normalize "${core_dir}/ICacheMSHR_6.sv" ]\
 [file normalize "${core_dir}/ICacheMSHR_7.sv" ]\
 [file normalize "${core_dir}/ICacheMSHR_8.sv" ]\
 [file normalize "${core_dir}/ICacheMSHR_9.sv" ]\
 [file normalize "${core_dir}/ICacheMSHR.sv" ]\
 [file normalize "${core_dir}/ICacheReplacer.sv" ]\
 [file normalize "${core_dir}/ICache.sv" ]\
 [file normalize "${core_dir}/IDPool.sv" ]\
 [file normalize "${core_dir}/ImmExtractor_12.sv" ]\
 [file normalize "${core_dir}/ImmExtractor_2.sv" ]\
 [file normalize "${core_dir}/ImmExtractor_37.sv" ]\
 [file normalize "${core_dir}/ImmExtractor_57.sv" ]\
 [file normalize "${core_dir}/ImmExtractor.sv" ]\
 [file normalize "${core_dir}/IMSICGateWay.sv" ]\
 [file normalize "${core_dir}/IMSIC.sv" ]\
 [file normalize "${core_dir}/IndexableCAMTemplate_16.sv" ]\
 [file normalize "${core_dir}/IndexableCAMTemplate_24.sv" ]\
 [file normalize "${core_dir}/IndexableCAMTemplate_25.sv" ]\
 [file normalize "${core_dir}/IndexableCAMTemplate_29.sv" ]\
 [file normalize "${core_dir}/IndexableCAMTemplate_31.sv" ]\
 [file normalize "${core_dir}/IndexableCAMTemplate.sv" ]\
 [file normalize "${core_dir}/indexedLSNumOfUopTable.sv" ]\
 [file normalize "${core_dir}/indexedLSUopTable_1.sv" ]\
 [file normalize "${core_dir}/indexedLSUopTable_2.sv" ]\
 [file normalize "${core_dir}/indexedLSUopTable_3.sv" ]\
 [file normalize "${core_dir}/indexedLSUopTable_4.sv" ]\
 [file normalize "${core_dir}/indexedLSUopTable_5.sv" ]\
 [file normalize "${core_dir}/indexedLSUopTable_6.sv" ]\
 [file normalize "${core_dir}/indexedLSUopTable_7.sv" ]\
 [file normalize "${core_dir}/IndirectCSRPermitModule.sv" ]\
 [file normalize "${core_dir}/instretModule.sv" ]\
 [file normalize "${core_dir}/InstrMMIOEntry.sv" ]\
 [file normalize "${core_dir}/InstrUncacheBuffer.sv" ]\
 [file normalize "${core_dir}/InstrUncache.sv" ]\
 [file normalize "${core_dir}/INT2FP.sv" ]\
 [file normalize "${core_dir}/IntBuffer.sv" ]\
 [file normalize "${core_dir}/InterruptFilter.sv" ]\
 [file normalize "${core_dir}/IntFile.sv" ]\
 [file normalize "${core_dir}/IntFPToVec.sv" ]\
 [file normalize "${core_dir}/IntRegFilePart0.sv" ]\
 [file normalize "${core_dir}/IntRegFilePart1.sv" ]\
 [file normalize "${core_dir}/IntRegFilePart2.sv" ]\
 [file normalize "${core_dir}/IntRegFilePart3.sv" ]\
 [file normalize "${core_dir}/IntRFReadArbiter.sv" ]\
 [file normalize "${core_dir}/IntRFWBCollideChecker.sv" ]\
 [file normalize "${core_dir}/IntToFP_1.sv" ]\
 [file normalize "${core_dir}/IntToFP_2.sv" ]\
 [file normalize "${core_dir}/IntToFP_3.sv" ]\
 [file normalize "${core_dir}/IntToFPDataModule.sv" ]\
 [file normalize "${core_dir}/IntToFP_postnorm_1.sv" ]\
 [file normalize "${core_dir}/IntToFP_postnorm_2.sv" ]\
 [file normalize "${core_dir}/IntToFP_postnorm.sv" ]\
 [file normalize "${core_dir}/IntToFP_prenorm.sv" ]\
 [file normalize "${core_dir}/IntToFP.sv" ]\
 [file normalize "${core_dir}/IPrefetchPipe.sv" ]\
 [file normalize "${core_dir}/Iprio0Module_1.sv" ]\
 [file normalize "${core_dir}/Iprio0Module.sv" ]\
 [file normalize "${core_dir}/Iprio10Module_1.sv" ]\
 [file normalize "${core_dir}/Iprio10Module.sv" ]\
 [file normalize "${core_dir}/Iprio12Module_1.sv" ]\
 [file normalize "${core_dir}/Iprio12Module.sv" ]\
 [file normalize "${core_dir}/Iprio14Module_1.sv" ]\
 [file normalize "${core_dir}/Iprio14Module.sv" ]\
 [file normalize "${core_dir}/Iprio2Module_1.sv" ]\
 [file normalize "${core_dir}/Iprio2Module.sv" ]\
 [file normalize "${core_dir}/Iprio4Module_1.sv" ]\
 [file normalize "${core_dir}/Iprio4Module.sv" ]\
 [file normalize "${core_dir}/Iprio6Module_1.sv" ]\
 [file normalize "${core_dir}/Iprio6Module.sv" ]\
 [file normalize "${core_dir}/Iprio8Module_1.sv" ]\
 [file normalize "${core_dir}/Iprio8Module.sv" ]\
 [file normalize "${core_dir}/IssueQueueAluBrhJmpI2fVsetriwiVsetriwvfI2v.sv" ]\
 [file normalize "${core_dir}/IssueQueueAluCsrFenceDiv.sv" ]\
 [file normalize "${core_dir}/IssueQueueAluMulBkuBrhJmp.sv" ]\
 [file normalize "${core_dir}/IssueQueueFaluFcvtF2vFmacFdiv.sv" ]\
 [file normalize "${core_dir}/IssueQueueFaluFmacFdiv.sv" ]\
 [file normalize "${core_dir}/IssueQueueFaluFmac.sv" ]\
 [file normalize "${core_dir}/IssueQueueLdu.sv" ]\
 [file normalize "${core_dir}/IssueQueueStaMou.sv" ]\
 [file normalize "${core_dir}/IssueQueueStdMoud.sv" ]\
 [file normalize "${core_dir}/IssueQueueVfdivVidiv.sv" ]\
 [file normalize "${core_dir}/IssueQueueVfmaVialuFixVfalu.sv" ]\
 [file normalize "${core_dir}/IssueQueueVfmaVialuFixVimacVppuVfaluVfcvtVipuVsetrvfwvf.sv" ]\
 [file normalize "${core_dir}/IssueQueueVlduVstu.sv" ]\
 [file normalize "${core_dir}/IssueQueueVlduVstuVseglduVsegstu.sv" ]\
 [file normalize "${core_dir}/IterBlockI8Nr4.sv" ]\
 [file normalize "${core_dir}/IterBlock_v4_4.sv" ]\
 [file normalize "${core_dir}/IterBlock_v4_6.sv" ]\
 [file normalize "${core_dir}/IterBlock_v4.sv" ]\
 [file normalize "${core_dir}/ITTage.sv" ]\
 [file normalize "${core_dir}/ITTageTable_1.sv" ]\
 [file normalize "${core_dir}/ITTageTable_2.sv" ]\
 [file normalize "${core_dir}/ITTageTable.sv" ]\
 [file normalize "${core_dir}/JtagBypassChain.sv" ]\
 [file normalize "${core_dir}/JtagStateMachine.sv" ]\
 [file normalize "${core_dir}/JtagTapController.sv" ]\
 [file normalize "${core_dir}/JumpDataModule.sv" ]\
 [file normalize "${core_dir}/JumpUnit.sv" ]\
 [file normalize "${core_dir}/L1CohMetaArray.sv" ]\
 [file normalize "${core_dir}/L1FlagMetaArray.sv" ]\
 [file normalize "${core_dir}/L1PrefetchSourceArray.sv" ]\
 [file normalize "${core_dir}/L2TlbMissQueue.sv" ]\
 [file normalize "${core_dir}/L2TlbPrefetch.sv" ]\
 [file normalize "${core_dir}/L2TLB.sv" ]\
 [file normalize "${core_dir}/L2TLBWrapper.sv" ]\
 [file normalize "${core_dir}/L2Top.sv" ]\
 [file normalize "${core_dir}/LatchFastArbiter_1.sv" ]\
 [file normalize "${core_dir}/LatchFastArbiter_2.sv" ]\
 [file normalize "${core_dir}/LatchFastArbiter_3.sv" ]\
 [file normalize "${core_dir}/LatchFastArbiter_4.sv" ]\
 [file normalize "${core_dir}/LatchFastArbiter_6.sv" ]\
 [file normalize "${core_dir}/LatchFastArbiter.sv" ]\
 [file normalize "${core_dir}/LazyModule.sv" ]\
 [file normalize "${core_dir}/LeftShiftModule.sv" ]\
 [file normalize "${core_dir}/LeftShiftWordModule.sv" ]\
 [file normalize "${core_dir}/LevelGateway.sv" ]\
 [file normalize "${core_dir}/LLPTW.sv" ]\
 [file normalize "${core_dir}/LoadMisalignBuffer.sv" ]\
 [file normalize "${core_dir}/LoadPipe.sv" ]\
 [file normalize "${core_dir}/LoadQueueRAR.sv" ]\
 [file normalize "${core_dir}/LoadQueueRAW.sv" ]\
 [file normalize "${core_dir}/LoadQueueReplay.sv" ]\
 [file normalize "${core_dir}/LoadQueue.sv" ]\
 [file normalize "${core_dir}/LoadQueueUncache.sv" ]\
 [file normalize "${core_dir}/LoadUnit.sv" ]\
 [file normalize "${core_dir}/LqExceptionBuffer.sv" ]\
 [file normalize "${core_dir}/LqMaskModule.sv" ]\
 [file normalize "${core_dir}/LqPAddrModule_1.sv" ]\
 [file normalize "${core_dir}/LqPAddrModule.sv" ]\
 [file normalize "${core_dir}/LqVAddrModule.sv" ]\
 [file normalize "${core_dir}/LsqEnqCtrl.sv" ]\
 [file normalize "${core_dir}/LsqWrapper.sv" ]\
 [file normalize "${core_dir}/LZA.sv" ]\
 [file normalize "${core_dir}/lzc_3.sv" ]\
 [file normalize "${core_dir}/lzc_4.sv" ]\
 [file normalize "${core_dir}/lzc.sv" ]\
 [file normalize "${core_dir}/MainPipe_1.sv" ]\
 [file normalize "${core_dir}/MainPipe.sv" ]\
 [file normalize "${core_dir}/MaskExtractor.sv" ]\
 [file normalize "${core_dir}/MaxPeriodFibonacciLFSR_3.sv" ]\
 [file normalize "${core_dir}/MaxPeriodFibonacciLFSR.sv" ]\
 [file normalize "${core_dir}/MbistClockGateCell_127.sv" ]\
 [file normalize "${core_dir}/MbistClockGateCell.sv" ]\
 [file normalize "${core_dir}/McauseModule.sv" ]\
 [file normalize "${core_dir}/MconfigptrModule.sv" ]\
 [file normalize "${core_dir}/McorepwrModule.sv" ]\
 [file normalize "${core_dir}/McounterenModule.sv" ]\
 [file normalize "${core_dir}/McountinhibitModule.sv" ]\
 [file normalize "${core_dir}/McycleModule.sv" ]\
 [file normalize "${core_dir}/MedelegModule.sv" ]\
 [file normalize "${core_dir}/MEFreeList.sv" ]\
 [file normalize "${core_dir}/MemBlock.sv" ]\
 [file normalize "${core_dir}/MemExeUnit.sv" ]\
 [file normalize "${core_dir}/MemTrigger_3.sv" ]\
 [file normalize "${core_dir}/MemTrigger.sv" ]\
 [file normalize "${core_dir}/MenvcfgModule.sv" ]\
 [file normalize "${core_dir}/MepcModule.sv" ]\
 [file normalize "${core_dir}/MflushpwrModule.sv" ]\
 [file normalize "${core_dir}/Mgtu.sv" ]\
 [file normalize "${core_dir}/Mgu.sv" ]\
 [file normalize "${core_dir}/MhartidModule.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter10Module.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter11Module.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter12Module.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter13Module.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter14Module.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter15Module.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter16Module.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter17Module.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter18Module.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter19Module.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter20Module.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter21Module.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter22Module.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter23Module.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter24Module.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter25Module.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter26Module.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter27Module.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter28Module.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter29Module.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter30Module.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter31Module.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter3Module.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter4Module.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter5Module.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter6Module.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter7Module.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter8Module.sv" ]\
 [file normalize "${core_dir}/Mhpmcounter9Module.sv" ]\
 [file normalize "${core_dir}/MhpmeventModule.sv" ]\
 [file normalize "${core_dir}/MidelegModule.sv" ]\
 [file normalize "${core_dir}/MieModule.sv" ]\
 [file normalize "${core_dir}/MinstretModule.sv" ]\
 [file normalize "${core_dir}/MipModule.sv" ]\
 [file normalize "${core_dir}/MiregModule.sv" ]\
 [file normalize "${core_dir}/MiscModule.sv" ]\
 [file normalize "${core_dir}/MiscResultSelect.sv" ]\
 [file normalize "${core_dir}/MiselectModule.sv" ]\
 [file normalize "${core_dir}/MissEntry.sv" ]\
 [file normalize "${core_dir}/MissQueue.sv" ]\
 [file normalize "${core_dir}/MissReadyGen.sv" ]\
 [file normalize "${core_dir}/MLevelPermitModule.sv" ]\
 [file normalize "${core_dir}/MncauseModule.sv" ]\
 [file normalize "${core_dir}/MnepcModule.sv" ]\
 [file normalize "${core_dir}/MNretEventModule.sv" ]\
 [file normalize "${core_dir}/MnscratchModule.sv" ]\
 [file normalize "${core_dir}/MnstatusModule.sv" ]\
 [file normalize "${core_dir}/Monitor.sv" ]\
 [file normalize "${core_dir}/MretEventModule.sv" ]\
 [file normalize "${core_dir}/MscratchModule.sv" ]\
 [file normalize "${core_dir}/MseccfgModule.sv" ]\
 [file normalize "${core_dir}/MSHR_32.sv" ]\
 [file normalize "${core_dir}/MSHRAlloc.sv" ]\
 [file normalize "${core_dir}/MSHRBuffer_1.sv" ]\
 [file normalize "${core_dir}/MSHRBuffer.sv" ]\
 [file normalize "${core_dir}/MSHRCtl.sv" ]\
 [file normalize "${core_dir}/MSHRSelector_2.sv" ]\
 [file normalize "${core_dir}/MSHRSelector.sv" ]\
 [file normalize "${core_dir}/MSHR.sv" ]\
 [file normalize "${core_dir}/MstateenModule.sv" ]\
 [file normalize "${core_dir}/MStatusModule.sv" ]\
 [file normalize "${core_dir}/MtinstModule.sv" ]\
 [file normalize "${core_dir}/MtopeiModule.sv" ]\
 [file normalize "${core_dir}/MtopiModule.sv" ]\
 [file normalize "${core_dir}/Mtval2Module.sv" ]\
 [file normalize "${core_dir}/MtvalModule.sv" ]\
 [file normalize "${core_dir}/MtvecModule.sv" ]\
 [file normalize "${core_dir}/MultiWakeupQueue_2.sv" ]\
 [file normalize "${core_dir}/MultiWakeupQueue_4.sv" ]\
 [file normalize "${core_dir}/MultiWakeupQueue_5.sv" ]\
 [file normalize "${core_dir}/MultiWakeupQueue.sv" ]\
 [file normalize "${core_dir}/MulUnit.sv" ]\
 [file normalize "${core_dir}/MuxBundle.sv" ]\
 [file normalize "${core_dir}/MvendoridModule.sv" ]\
 [file normalize "${core_dir}/MvienModule.sv" ]\
 [file normalize "${core_dir}/MvipModule.sv" ]\
 [file normalize "${core_dir}/NewAgeDetector_6.sv" ]\
 [file normalize "${core_dir}/NewAgeDetector.sv" ]\
 [file normalize "${core_dir}/NewCSR.sv" ]\
 [file normalize "${core_dir}/NewDispatch.sv" ]\
 [file normalize "${core_dir}/NewIFU.sv" ]\
 [file normalize "${core_dir}/NewPipelineConnectPipe_10.sv" ]\
 [file normalize "${core_dir}/NewPipelineConnectPipe_13.sv" ]\
 [file normalize "${core_dir}/NewPipelineConnectPipe_14.sv" ]\
 [file normalize "${core_dir}/NewPipelineConnectPipe_16.sv" ]\
 [file normalize "${core_dir}/NewPipelineConnectPipe_18.sv" ]\
 [file normalize "${core_dir}/NewPipelineConnectPipe_1.sv" ]\
 [file normalize "${core_dir}/NewPipelineConnectPipe_20.sv" ]\
 [file normalize "${core_dir}/NewPipelineConnectPipe_23.sv" ]\
 [file normalize "${core_dir}/NewPipelineConnectPipe_25.sv" ]\
 [file normalize "${core_dir}/NewPipelineConnectPipe_27.sv" ]\
 [file normalize "${core_dir}/NewPipelineConnectPipe_31.sv" ]\
 [file normalize "${core_dir}/NewPipelineConnectPipe_32.sv" ]\
 [file normalize "${core_dir}/NewPipelineConnectPipe_33.sv" ]\
 [file normalize "${core_dir}/NewPipelineConnectPipe_35.sv" ]\
 [file normalize "${core_dir}/NewPipelineConnectPipe_5.sv" ]\
 [file normalize "${core_dir}/NewPipelineConnectPipe_7.sv" ]\
 [file normalize "${core_dir}/NewPipelineConnectPipe_8.sv" ]\
 [file normalize "${core_dir}/NewPipelineConnectPipe_9.sv" ]\
 [file normalize "${core_dir}/NewPipelineConnectPipe.sv" ]\
 [file normalize "${core_dir}/NewRobDeqPtrWrapper.sv" ]\
 [file normalize "${core_dir}/NfMappedElemIdx.sv" ]\
 [file normalize "${core_dir}/Og2ForVector.sv" ]\
 [file normalize "${core_dir}/OthersEntry_108.sv" ]\
 [file normalize "${core_dir}/OthersEntry_110.sv" ]\
 [file normalize "${core_dir}/OthersEntry_116.sv" ]\
 [file normalize "${core_dir}/OthersEntry_118.sv" ]\
 [file normalize "${core_dir}/OthersEntry_144.sv" ]\
 [file normalize "${core_dir}/OthersEntry_146.sv" ]\
 [file normalize "${core_dir}/OthersEntry_16.sv" ]\
 [file normalize "${core_dir}/OthersEntry_186.sv" ]\
 [file normalize "${core_dir}/OthersEntry_188.sv" ]\
 [file normalize "${core_dir}/OthersEntry_20.sv" ]\
 [file normalize "${core_dir}/OthersEntry_24.sv" ]\
 [file normalize "${core_dir}/OthersEntry_28.sv" ]\
 [file normalize "${core_dir}/OthersEntry_32.sv" ]\
 [file normalize "${core_dir}/OthersEntry_34.sv" ]\
 [file normalize "${core_dir}/OthersEntry_48.sv" ]\
 [file normalize "${core_dir}/OthersEntry_4.sv" ]\
 [file normalize "${core_dir}/OthersEntry_50.sv" ]\
 [file normalize "${core_dir}/OthersEntry_64.sv" ]\
 [file normalize "${core_dir}/OthersEntry_66.sv" ]\
 [file normalize "${core_dir}/OthersEntry_80.sv" ]\
 [file normalize "${core_dir}/OthersEntry_82.sv" ]\
 [file normalize "${core_dir}/OthersEntry_94.sv" ]\
 [file normalize "${core_dir}/OthersEntry_96.sv" ]\
 [file normalize "${core_dir}/OthersEntry.sv" ]\
 [file normalize "${core_dir}/OthersEntryVecMem_14.sv" ]\
 [file normalize "${core_dir}/OthersEntryVecMem_16.sv" ]\
 [file normalize "${core_dir}/OthersEntryVecMem_2.sv" ]\
 [file normalize "${core_dir}/OthersEntryVecMem.sv" ]\
 [file normalize "${core_dir}/perfEventsModule.sv" ]\
 [file normalize "${core_dir}/Permutation.sv" ]\
 [file normalize "${core_dir}/PFEvent.sv" ]\
 [file normalize "${core_dir}/PipeGroupConnect.sv" ]\
 [file normalize "${core_dir}/Pipeline_2.sv" ]\
 [file normalize "${core_dir}/Pipeline_3.sv" ]\
 [file normalize "${core_dir}/Pipeline_4.sv" ]\
 [file normalize "${core_dir}/Pipeline_5.sv" ]\
 [file normalize "${core_dir}/Pipeline_6.sv" ]\
 [file normalize "${core_dir}/PipelineConnectPipe.sv" ]\
 [file normalize "${core_dir}/PipelineRegModule_1.sv" ]\
 [file normalize "${core_dir}/PipelineRegModule_2.sv" ]\
 [file normalize "${core_dir}/PipelineRegModule_6.sv" ]\
 [file normalize "${core_dir}/PipelineRegModule.sv" ]\
 [file normalize "${core_dir}/PipeWithFlush_10.sv" ]\
 [file normalize "${core_dir}/PipeWithFlush_11.sv" ]\
 [file normalize "${core_dir}/PipeWithFlush_1.sv" ]\
 [file normalize "${core_dir}/PipeWithFlush_6.sv" ]\
 [file normalize "${core_dir}/PipeWithFlush_7.sv" ]\
 [file normalize "${core_dir}/PipeWithFlush_8.sv" ]\
 [file normalize "${core_dir}/PipeWithFlush_9.sv" ]\
 [file normalize "${core_dir}/PipeWithFlush.sv" ]\
 [file normalize "${core_dir}/PLICFanIn.sv" ]\
 [file normalize "${core_dir}/Pma0cfgModule.sv" ]\
 [file normalize "${core_dir}/Pma10cfgModule.sv" ]\
 [file normalize "${core_dir}/Pma11cfgModule.sv" ]\
 [file normalize "${core_dir}/Pma12cfgModule.sv" ]\
 [file normalize "${core_dir}/Pma13cfgModule.sv" ]\
 [file normalize "${core_dir}/Pma14cfgModule.sv" ]\
 [file normalize "${core_dir}/Pma15cfgModule.sv" ]\
 [file normalize "${core_dir}/Pma1cfgModule.sv" ]\
 [file normalize "${core_dir}/Pma2cfgModule.sv" ]\
 [file normalize "${core_dir}/Pma3cfgModule.sv" ]\
 [file normalize "${core_dir}/Pma4cfgModule.sv" ]\
 [file normalize "${core_dir}/Pma5cfgModule.sv" ]\
 [file normalize "${core_dir}/Pma6cfgModule.sv" ]\
 [file normalize "${core_dir}/Pma7cfgModule.sv" ]\
 [file normalize "${core_dir}/Pma8cfgModule.sv" ]\
 [file normalize "${core_dir}/Pma9cfgModule.sv" ]\
 [file normalize "${core_dir}/Pmaaddr0Module.sv" ]\
 [file normalize "${core_dir}/Pmaaddr10Module.sv" ]\
 [file normalize "${core_dir}/Pmaaddr11Module.sv" ]\
 [file normalize "${core_dir}/Pmaaddr12Module.sv" ]\
 [file normalize "${core_dir}/Pmaaddr13Module.sv" ]\
 [file normalize "${core_dir}/Pmaaddr14Module.sv" ]\
 [file normalize "${core_dir}/Pmaaddr15Module.sv" ]\
 [file normalize "${core_dir}/Pmaaddr1Module.sv" ]\
 [file normalize "${core_dir}/Pmaaddr2Module.sv" ]\
 [file normalize "${core_dir}/Pmaaddr3Module.sv" ]\
 [file normalize "${core_dir}/Pmaaddr4Module.sv" ]\
 [file normalize "${core_dir}/Pmaaddr5Module.sv" ]\
 [file normalize "${core_dir}/Pmaaddr6Module.sv" ]\
 [file normalize "${core_dir}/Pmaaddr7Module.sv" ]\
 [file normalize "${core_dir}/Pmaaddr8Module.sv" ]\
 [file normalize "${core_dir}/Pmaaddr9Module.sv" ]\
 [file normalize "${core_dir}/Pmacfg0Module.sv" ]\
 [file normalize "${core_dir}/Pmacfg2Module.sv" ]\
 [file normalize "${core_dir}/PMAEntryHandleModule.sv" ]\
 [file normalize "${core_dir}/Pmp0cfgModule.sv" ]\
 [file normalize "${core_dir}/Pmp10cfgModule.sv" ]\
 [file normalize "${core_dir}/Pmp11cfgModule.sv" ]\
 [file normalize "${core_dir}/Pmp12cfgModule.sv" ]\
 [file normalize "${core_dir}/Pmp13cfgModule.sv" ]\
 [file normalize "${core_dir}/Pmp14cfgModule.sv" ]\
 [file normalize "${core_dir}/Pmp15cfgModule.sv" ]\
 [file normalize "${core_dir}/Pmp1cfgModule.sv" ]\
 [file normalize "${core_dir}/Pmp2cfgModule.sv" ]\
 [file normalize "${core_dir}/Pmp3cfgModule.sv" ]\
 [file normalize "${core_dir}/Pmp4cfgModule.sv" ]\
 [file normalize "${core_dir}/Pmp5cfgModule.sv" ]\
 [file normalize "${core_dir}/Pmp6cfgModule.sv" ]\
 [file normalize "${core_dir}/Pmp7cfgModule.sv" ]\
 [file normalize "${core_dir}/Pmp8cfgModule.sv" ]\
 [file normalize "${core_dir}/Pmp9cfgModule.sv" ]\
 [file normalize "${core_dir}/Pmpaddr0Module.sv" ]\
 [file normalize "${core_dir}/Pmpaddr10Module.sv" ]\
 [file normalize "${core_dir}/Pmpaddr11Module.sv" ]\
 [file normalize "${core_dir}/Pmpaddr12Module.sv" ]\
 [file normalize "${core_dir}/Pmpaddr13Module.sv" ]\
 [file normalize "${core_dir}/Pmpaddr14Module.sv" ]\
 [file normalize "${core_dir}/Pmpaddr15Module.sv" ]\
 [file normalize "${core_dir}/Pmpaddr1Module.sv" ]\
 [file normalize "${core_dir}/Pmpaddr2Module.sv" ]\
 [file normalize "${core_dir}/Pmpaddr3Module.sv" ]\
 [file normalize "${core_dir}/Pmpaddr4Module.sv" ]\
 [file normalize "${core_dir}/Pmpaddr5Module.sv" ]\
 [file normalize "${core_dir}/Pmpaddr6Module.sv" ]\
 [file normalize "${core_dir}/Pmpaddr7Module.sv" ]\
 [file normalize "${core_dir}/Pmpaddr8Module.sv" ]\
 [file normalize "${core_dir}/Pmpaddr9Module.sv" ]\
 [file normalize "${core_dir}/Pmpcfg0Module.sv" ]\
 [file normalize "${core_dir}/Pmpcfg2Module.sv" ]\
 [file normalize "${core_dir}/PMPChecker_10.sv" ]\
 [file normalize "${core_dir}/PMPChecker.sv" ]\
 [file normalize "${core_dir}/PMPEntryHandleModule.sv" ]\
 [file normalize "${core_dir}/PMP.sv" ]\
 [file normalize "${core_dir}/PredChecker.sv" ]\
 [file normalize "${core_dir}/PreDecode.sv" ]\
 [file normalize "${core_dir}/Predictor.sv" ]\
 [file normalize "${core_dir}/PrefetchBurstGenerator.sv" ]\
 [file normalize "${core_dir}/PreprocessEndpoint.sv" ]\
 [file normalize "${core_dir}/PrintCommitIDModule.v" ]\
 [file normalize "${core_dir}/PriorityMuxModule_12.sv" ]\
 [file normalize "${core_dir}/PriorityMuxModule_16.sv" ]\
 [file normalize "${core_dir}/PriorityMuxModule_20.sv" ]\
 [file normalize "${core_dir}/PriorityMuxModule_4.sv" ]\
 [file normalize "${core_dir}/PriorityMuxModule_8.sv" ]\
 [file normalize "${core_dir}/PriorityMuxModule.sv" ]\
 [file normalize "${core_dir}/PrivilegePermitModule.sv" ]\
 [file normalize "${core_dir}/ProbeEntry.sv" ]\
 [file normalize "${core_dir}/ProbeHelper.sv" ]\
 [file normalize "${core_dir}/ProbeQueue.sv" ]\
 [file normalize "${core_dir}/PtwCache.sv" ]\
 [file normalize "${core_dir}/PTWFilterEntry_1.sv" ]\
 [file normalize "${core_dir}/PTWFilterEntry.sv" ]\
 [file normalize "${core_dir}/PTWFilter.sv" ]\
 [file normalize "${core_dir}/PTWNewFilter.sv" ]\
 [file normalize "${core_dir}/PTWRepeaterNB.sv" ]\
 [file normalize "${core_dir}/PTW.sv" ]\
 [file normalize "${core_dir}/Queue16_DSBeat.sv" ]\
 [file normalize "${core_dir}/Queue16_grantAckQEntry.sv" ]\
 [file normalize "${core_dir}/Queue16_GrantQueueData.sv" ]\
 [file normalize "${core_dir}/Queue16_GrantQueueTask.sv" ]\
 [file normalize "${core_dir}/Queue16_HintQueueEntry.sv" ]\
 [file normalize "${core_dir}/Queue16_TaskBundle.sv" ]\
 [file normalize "${core_dir}/Queue1_AXI4BundleAR.sv" ]\
 [file normalize "${core_dir}/Queue1_AXI4BundleARW_1.sv" ]\
 [file normalize "${core_dir}/Queue1_AXI4BundleARW.sv" ]\
 [file normalize "${core_dir}/Queue1_AXI4BundleAW.sv" ]\
 [file normalize "${core_dir}/Queue1_AXI4BundleB.sv" ]\
 [file normalize "${core_dir}/Queue1_AXI4BundleR.sv" ]\
 [file normalize "${core_dir}/Queue1_AXI4BundleW_1.sv" ]\
 [file normalize "${core_dir}/Queue1_AXI4BundleW.sv" ]\
 [file normalize "${core_dir}/Queue1_BundleMap_74.sv" ]\
 [file normalize "${core_dir}/Queue1_BundleMap_80.sv" ]\
 [file normalize "${core_dir}/Queue1_BundleMap_90.sv" ]\
 [file normalize "${core_dir}/Queue1_BundleMap.sv" ]\
 [file normalize "${core_dir}/Queue1_ChosenQBundle.sv" ]\
 [file normalize "${core_dir}/Queue1_ClientDirWrite.sv" ]\
 [file normalize "${core_dir}/Queue1_ClientTagWrite.sv" ]\
 [file normalize "${core_dir}/Queue1_MSHRRequest.sv" ]\
 [file normalize "${core_dir}/Queue1_PipeInfo.sv" ]\
 [file normalize "${core_dir}/Queue1_RegMapperInput_1.sv" ]\
 [file normalize "${core_dir}/Queue1_RegMapperInput_3.sv" ]\
 [file normalize "${core_dir}/Queue1_RegMapperInput_4.sv" ]\
 [file normalize "${core_dir}/Queue1_RegMapperInput.sv" ]\
 [file normalize "${core_dir}/Queue1_SelfDirWrite.sv" ]\
 [file normalize "${core_dir}/Queue1_SelfTagWrite.sv" ]\
 [file normalize "${core_dir}/Queue1_TLBundleA.sv" ]\
 [file normalize "${core_dir}/Queue2_AXI4BundleAR_3.sv" ]\
 [file normalize "${core_dir}/Queue2_AXI4BundleAR_7.sv" ]\
 [file normalize "${core_dir}/Queue2_AXI4BundleAR.sv" ]\
 [file normalize "${core_dir}/Queue2_AXI4BundleAW_3.sv" ]\
 [file normalize "${core_dir}/Queue2_AXI4BundleAW_7.sv" ]\
 [file normalize "${core_dir}/Queue2_AXI4BundleAW.sv" ]\
 [file normalize "${core_dir}/Queue2_AXI4BundleB_3.sv" ]\
 [file normalize "${core_dir}/Queue2_AXI4BundleB_7.sv" ]\
 [file normalize "${core_dir}/Queue2_AXI4BundleB.sv" ]\
 [file normalize "${core_dir}/Queue2_AXI4BundleR_3.sv" ]\
 [file normalize "${core_dir}/Queue2_AXI4BundleR_40.sv" ]\
 [file normalize "${core_dir}/Queue2_AXI4BundleR_44.sv" ]\
 [file normalize "${core_dir}/Queue2_AXI4BundleR_45.sv" ]\
 [file normalize "${core_dir}/Queue2_AXI4BundleR.sv" ]\
 [file normalize "${core_dir}/Queue2_AXI4BundleW_3.sv" ]\
 [file normalize "${core_dir}/Queue2_AXI4BundleW.sv" ]\
 [file normalize "${core_dir}/Queue2_BundleMap.sv" ]\
 [file normalize "${core_dir}/Queue2_DSData.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleA_10.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleA_14.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleA_15.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleA_16.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleA_20.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleA_21.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleA_22.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleA_26.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleA_28.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleA_29.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleA_2.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleA_33.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleA_37.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleA_46.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleA_5.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleA_7.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleA.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleB_1.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleB_2.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleB_4.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleB.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleC_1.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleC_2.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleC_4.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleC.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleD_12.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleD_16.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleD_17.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleD_18.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleD_19.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleD_23.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleD_24.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleD_25.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleD_29.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleD_2.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleD_31.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleD_32.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleD_36.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleD_40.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleD_4.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleD_7.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleD.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleE_1.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleE_2.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleE_6.sv" ]\
 [file normalize "${core_dir}/Queue2_TLBundleE.sv" ]\
 [file normalize "${core_dir}/Queue40_L2TlbMQBundle.sv" ]\
 [file normalize "${core_dir}/Queue4_DSData.sv" ]\
 [file normalize "${core_dir}/Queue4_HintQueueEntry.sv" ]\
 [file normalize "${core_dir}/Queue5_MSHRRequest.sv" ]\
 [file normalize "${core_dir}/Queue6_PutBufferBeatEntry.sv" ]\
 [file normalize "${core_dir}/Queue7_TLBundleC.sv" ]\
 [file normalize "${core_dir}/r4_qds_cg.sv" ]\
 [file normalize "${core_dir}/r4_qds_spec.sv" ]\
 [file normalize "${core_dir}/r4_qds.sv" ]\
 [file normalize "${core_dir}/r4_qds_v2_spec.sv" ]\
 [file normalize "${core_dir}/r4_qds_v2.sv" ]\
 [file normalize "${core_dir}/ram_16x10.sv" ]\
 [file normalize "${core_dir}/ram_16x24.sv" ]\
 [file normalize "${core_dir}/ram_16x4.sv" ]\
 [file normalize "${core_dir}/ram_16x63.sv" ]\
 [file normalize "${core_dir}/ram_2x10.sv" ]\
 [file normalize "${core_dir}/ram_2x114.sv" ]\
 [file normalize "${core_dir}/ram_2x115.sv" ]\
 [file normalize "${core_dir}/ram_2x117.sv" ]\
 [file normalize "${core_dir}/ram_2x132.sv" ]\
 [file normalize "${core_dir}/ram_2x133.sv" ]\
 [file normalize "${core_dir}/ram_2x134.sv" ]\
 [file normalize "${core_dir}/ram_2x16.sv" ]\
 [file normalize "${core_dir}/ram_2x256.sv" ]\
 [file normalize "${core_dir}/ram_2x272.sv" ]\
 [file normalize "${core_dir}/ram_2x273.sv" ]\
 [file normalize "${core_dir}/ram_2x274.sv" ]\
 [file normalize "${core_dir}/ram_2x275.sv" ]\
 [file normalize "${core_dir}/ram_2x279.sv" ]\
 [file normalize "${core_dir}/ram_2x280.sv" ]\
 [file normalize "${core_dir}/ram_2x281.sv" ]\
 [file normalize "${core_dir}/ram_2x282.sv" ]\
 [file normalize "${core_dir}/ram_2x289.sv" ]\
 [file normalize "${core_dir}/ram_2x312.sv" ]\
 [file normalize "${core_dir}/ram_2x315.sv" ]\
 [file normalize "${core_dir}/ram_2x323.sv" ]\
 [file normalize "${core_dir}/ram_2x345.sv" ]\
 [file normalize "${core_dir}/ram_2x348.sv" ]\
 [file normalize "${core_dir}/ram_2x350.sv" ]\
 [file normalize "${core_dir}/ram_2x351.sv" ]\
 [file normalize "${core_dir}/ram_2x352.sv" ]\
 [file normalize "${core_dir}/ram_2x353.sv" ]\
 [file normalize "${core_dir}/ram_2x355.sv" ]\
 [file normalize "${core_dir}/ram_2x356.sv" ]\
 [file normalize "${core_dir}/ram_2x357.sv" ]\
 [file normalize "${core_dir}/ram_2x369.sv" ]\
 [file normalize "${core_dir}/ram_2x371.sv" ]\
 [file normalize "${core_dir}/ram_2x402.sv" ]\
 [file normalize "${core_dir}/ram_2x404.sv" ]\
 [file normalize "${core_dir}/ram_2x59.sv" ]\
 [file normalize "${core_dir}/ram_2x5.sv" ]\
 [file normalize "${core_dir}/ram_2x70.sv" ]\
 [file normalize "${core_dir}/ram_2x73.sv" ]\
 [file normalize "${core_dir}/ram_2x77.sv" ]\
 [file normalize "${core_dir}/ram_2x78.sv" ]\
 [file normalize "${core_dir}/ram_2x79.sv" ]\
 [file normalize "${core_dir}/ram_2x87.sv" ]\
 [file normalize "${core_dir}/ram_40x47.sv" ]\
 [file normalize "${core_dir}/ram_4x10.sv" ]\
 [file normalize "${core_dir}/ram_4x257.sv" ]\
 [file normalize "${core_dir}/ram_5x116.sv" ]\
 [file normalize "${core_dir}/ram_6x288.sv" ]\
 [file normalize "${core_dir}/ram_7x318.sv" ]\
 [file normalize "${core_dir}/ram_data_16x256.sv" ]\
 [file normalize "${core_dir}/ram_extra_id_2x1.sv" ]\
 [file normalize "${core_dir}/ram_sink_2x3.sv" ]\
 [file normalize "${core_dir}/ram_sink_2x4.sv" ]\
 [file normalize "${core_dir}/ram_sink_2x8.sv" ]\
 [file normalize "${core_dir}/ram_sink_2x9.sv" ]\
 [file normalize "${core_dir}/RASStack.sv" ]\
 [file normalize "${core_dir}/RAS.sv" ]\
 [file normalize "${core_dir}/RealWBArbiter_13.sv" ]\
 [file normalize "${core_dir}/RealWBArbiter_14.sv" ]\
 [file normalize "${core_dir}/RealWBArbiter_15.sv" ]\
 [file normalize "${core_dir}/RealWBArbiter_1.sv" ]\
 [file normalize "${core_dir}/RealWBArbiter_20.sv" ]\
 [file normalize "${core_dir}/RealWBArbiter_21.sv" ]\
 [file normalize "${core_dir}/RealWBArbiter_26.sv" ]\
 [file normalize "${core_dir}/RealWBArbiter_2.sv" ]\
 [file normalize "${core_dir}/RealWBArbiter_3.sv" ]\
 [file normalize "${core_dir}/RealWBArbiter_8.sv" ]\
 [file normalize "${core_dir}/RealWBArbiter.sv" ]\
 [file normalize "${core_dir}/RealWBCollideChecker_1.sv" ]\
 [file normalize "${core_dir}/RealWBCollideChecker_2.sv" ]\
 [file normalize "${core_dir}/RealWBCollideChecker_3.sv" ]\
 [file normalize "${core_dir}/RealWBCollideChecker_4.sv" ]\
 [file normalize "${core_dir}/RealWBCollideChecker.sv" ]\
 [file normalize "${core_dir}/Rec7Table.sv" ]\
 [file normalize "${core_dir}/RedirectGenerator.sv" ]\
 [file normalize "${core_dir}/Reduction.sv" ]\
 [file normalize "${core_dir}/RefillBuffer.sv" ]\
 [file normalize "${core_dir}/RefillUnit.sv" ]\
 [file normalize "${core_dir}/RegCacheAgeDetector_1.sv" ]\
 [file normalize "${core_dir}/RegCacheAgeDetector.sv" ]\
 [file normalize "${core_dir}/RegCacheAgeTimer_1.sv" ]\
 [file normalize "${core_dir}/RegCacheAgeTimer.sv" ]\
 [file normalize "${core_dir}/RegCacheDataModule_1.sv" ]\
 [file normalize "${core_dir}/RegCacheDataModule.sv" ]\
 [file normalize "${core_dir}/RegCache.sv" ]\
 [file normalize "${core_dir}/RegCacheTagModule_1.sv" ]\
 [file normalize "${core_dir}/RegCacheTagModule.sv" ]\
 [file normalize "${core_dir}/RegCacheTagTable.sv" ]\
 [file normalize "${core_dir}/RegionWays.sv" ]\
 [file normalize "${core_dir}/RenameBuffer.sv" ]\
 [file normalize "${core_dir}/Rename.sv" ]\
 [file normalize "${core_dir}/RenameTable_1.sv" ]\
 [file normalize "${core_dir}/RenameTable_2.sv" ]\
 [file normalize "${core_dir}/RenameTable_3.sv" ]\
 [file normalize "${core_dir}/RenameTable.sv" ]\
 [file normalize "${core_dir}/RenameTableWrapper.sv" ]\
 [file normalize "${core_dir}/Repeater_1.sv" ]\
 [file normalize "${core_dir}/Repeater.sv" ]\
 [file normalize "${core_dir}/RequestArb.sv" ]\
 [file normalize "${core_dir}/RequestBuffer_2.sv" ]\
 [file normalize "${core_dir}/RequestBuffer.sv" ]\
 [file normalize "${core_dir}/ResetGen_1.sv" ]\
 [file normalize "${core_dir}/ResetGen.sv" ]\
 [file normalize "${core_dir}/RightShifter.sv" ]\
 [file normalize "${core_dir}/RightShiftModule.sv" ]\
 [file normalize "${core_dir}/RightShiftWordModule.sv" ]\
 [file normalize "${core_dir}/RobEnqPtrWrapper.sv" ]\
 [file normalize "${core_dir}/Rob.sv" ]\
 [file normalize "${core_dir}/RoundingUnit_11.sv" ]\
 [file normalize "${core_dir}/RoundingUnit_1.sv" ]\
 [file normalize "${core_dir}/RoundingUnit_2.sv" ]\
 [file normalize "${core_dir}/RoundingUnit_3.sv" ]\
 [file normalize "${core_dir}/RoundingUnit_4.sv" ]\
 [file normalize "${core_dir}/RoundingUnit_8.sv" ]\
 [file normalize "${core_dir}/RoundingUnit_9.sv" ]\
 [file normalize "${core_dir}/RoundingUnit.sv" ]\
 [file normalize "${core_dir}/RRArbiterInit_3.sv" ]\
 [file normalize "${core_dir}/RRArbiterInit_4.sv" ]\
 [file normalize "${core_dir}/RRArbiterInit_5.sv" ]\
 [file normalize "${core_dir}/RRArbiterInit.sv" ]\
 [file normalize "${core_dir}/Rsqrt7Table.sv" ]\
 [file normalize "${core_dir}/RVCExpander.sv" ]\
 [file normalize "${core_dir}/SatpModule.sv" ]\
 [file normalize "${core_dir}/SbpctlModule.sv" ]\
 [file normalize "${core_dir}/SBToTL.sv" ]\
 [file normalize "${core_dir}/SbufferData.sv" ]\
 [file normalize "${core_dir}/Sbuffer.sv" ]\
 [file normalize "${core_dir}/ScauseModule.sv" ]\
 [file normalize "${core_dir}/Scheduler_1.sv" ]\
 [file normalize "${core_dir}/Scheduler_2.sv" ]\
 [file normalize "${core_dir}/Scheduler_3.sv" ]\
 [file normalize "${core_dir}/Scheduler.sv" ]\
 [file normalize "${core_dir}/ScounterenModule.sv" ]\
 [file normalize "${core_dir}/ScountovfModule.sv" ]\
 [file normalize "${core_dir}/SCTable_1.sv" ]\
 [file normalize "${core_dir}/SCTable.sv" ]\
 [file normalize "${core_dir}/SelBlock_v4.sv" ]\
 [file normalize "${core_dir}/SenvcfgModule.sv" ]\
 [file normalize "${core_dir}/SepcModule.sv" ]\
 [file normalize "${core_dir}/ShiftLeftPriorityWithF32EXPResult.sv" ]\
 [file normalize "${core_dir}/ShiftLeftPriorityWithF64EXPResult.sv" ]\
 [file normalize "${core_dir}/ShiftLeftPriorityWithLZDResult_6.sv" ]\
 [file normalize "${core_dir}/ShiftLeftPriorityWithLZDResult_8.sv" ]\
 [file normalize "${core_dir}/ShiftLeftPriorityWithLZDResult.sv" ]\
 [file normalize "${core_dir}/ShiftResultSelect.sv" ]\
 [file normalize "${core_dir}/ShiftRightJam_2.sv" ]\
 [file normalize "${core_dir}/ShiftRightJam_3.sv" ]\
 [file normalize "${core_dir}/ShiftRightJam_4.sv" ]\
 [file normalize "${core_dir}/ShiftRightJam.sv" ]\
 [file normalize "${core_dir}/SieModule.sv" ]\
 [file normalize "${core_dir}/SignDec.sv" ]\
 [file normalize "${core_dir}/SinkA_2.sv" ]\
 [file normalize "${core_dir}/SinkA.sv" ]\
 [file normalize "${core_dir}/SinkB_2.sv" ]\
 [file normalize "${core_dir}/SinkB.sv" ]\
 [file normalize "${core_dir}/SinkC_2.sv" ]\
 [file normalize "${core_dir}/SinkC.sv" ]\
 [file normalize "${core_dir}/SinkD.sv" ]\
 [file normalize "${core_dir}/SinkE.sv" ]\
 [file normalize "${core_dir}/SipModule.sv" ]\
 [file normalize "${core_dir}/SiregModule.sv" ]\
 [file normalize "${core_dir}/SiselectModule.sv" ]\
 [file normalize "${core_dir}/skidBufferConnect.sv" ]\
 [file normalize "${core_dir}/SLevelPermitModule.sv" ]\
 [file normalize "${core_dir}/Slice_2.sv" ]\
 [file normalize "${core_dir}/Slice.sv" ]\
 [file normalize "${core_dir}/slidednVs2VdTable.sv" ]\
 [file normalize "${core_dir}/slideupVs2VdTable.sv" ]\
 [file normalize "${core_dir}/SlvpredctlModule.sv" ]\
 [file normalize "${core_dir}/SmblockctlModule.sv" ]\
 [file normalize "${core_dir}/SnapshotGenerator_10.sv" ]\
 [file normalize "${core_dir}/SnapshotGenerator_12.sv" ]\
 [file normalize "${core_dir}/SnapshotGenerator_14.sv" ]\
 [file normalize "${core_dir}/SnapshotGenerator_1.sv" ]\
 [file normalize "${core_dir}/SnapshotGenerator_2.sv" ]\
 [file normalize "${core_dir}/SnapshotGenerator_3.sv" ]\
 [file normalize "${core_dir}/SnapshotGenerator_4.sv" ]\
 [file normalize "${core_dir}/SnapshotGenerator_5.sv" ]\
 [file normalize "${core_dir}/SnapshotGenerator_6.sv" ]\
 [file normalize "${core_dir}/SnapshotGenerator_7.sv" ]\
 [file normalize "${core_dir}/SnapshotGenerator.sv" ]\
 [file normalize "${core_dir}/SoCMisc.sv" ]\
 [file normalize "${core_dir}/SourceA.sv" ]\
 [file normalize "${core_dir}/SourceB_2.sv" ]\
 [file normalize "${core_dir}/SourceB.sv" ]\
 [file normalize "${core_dir}/SourceC_2.sv" ]\
 [file normalize "${core_dir}/SourceC.sv" ]\
 [file normalize "${core_dir}/SourceD.sv" ]\
 [file normalize "${core_dir}/SourceE.sv" ]\
 [file normalize "${core_dir}/SpecBlock_v4.sv" ]\
 [file normalize "${core_dir}/SpfctlModule.sv" ]\
 [file normalize "${core_dir}/SplittedSRAM_1.sv" ]\
 [file normalize "${core_dir}/SplittedSRAM_2.sv" ]\
 [file normalize "${core_dir}/SplittedSRAM.sv" ]\
 [file normalize "${core_dir}/SplittedSRAMTemplate_13.sv" ]\
 [file normalize "${core_dir}/SplittedSRAMTemplate_14.sv" ]\
 [file normalize "${core_dir}/SplittedSRAMTemplate_18.sv" ]\
 [file normalize "${core_dir}/SplittedSRAMTemplate_19.sv" ]\
 [file normalize "${core_dir}/SplittedSRAMTemplate_21.sv" ]\
 [file normalize "${core_dir}/SplittedSRAMTemplate_22.sv" ]\
 [file normalize "${core_dir}/SplittedSRAMTemplate_2.sv" ]\
 [file normalize "${core_dir}/SplittedSRAMTemplate_3.sv" ]\
 [file normalize "${core_dir}/SplittedSRAMTemplate_4.sv" ]\
 [file normalize "${core_dir}/SplittedSRAMTemplate.sv" ]\
 [file normalize "${core_dir}/SQAddrModule_1.sv" ]\
 [file normalize "${core_dir}/SQAddrModule.sv" ]\
 [file normalize "${core_dir}/SQData8Module.sv" ]\
 [file normalize "${core_dir}/SQDataModule.sv" ]\
 [file normalize "${core_dir}/SquashControl.v" ]\
 [file normalize "${core_dir}/SquashEndpoint.sv" ]\
 [file normalize "${core_dir}/Squasher_10.sv" ]\
 [file normalize "${core_dir}/Squasher_11.sv" ]\
 [file normalize "${core_dir}/Squasher_12.sv" ]\
 [file normalize "${core_dir}/Squasher_13.sv" ]\
 [file normalize "${core_dir}/Squasher_14.sv" ]\
 [file normalize "${core_dir}/Squasher_15.sv" ]\
 [file normalize "${core_dir}/Squasher_16.sv" ]\
 [file normalize "${core_dir}/Squasher_17.sv" ]\
 [file normalize "${core_dir}/Squasher_18.sv" ]\
 [file normalize "${core_dir}/Squasher_19.sv" ]\
 [file normalize "${core_dir}/Squasher_1.sv" ]\
 [file normalize "${core_dir}/Squasher_20.sv" ]\
 [file normalize "${core_dir}/Squasher_21.sv" ]\
 [file normalize "${core_dir}/Squasher_22.sv" ]\
 [file normalize "${core_dir}/Squasher_23.sv" ]\
 [file normalize "${core_dir}/Squasher_24.sv" ]\
 [file normalize "${core_dir}/Squasher_25.sv" ]\
 [file normalize "${core_dir}/Squasher_26.sv" ]\
 [file normalize "${core_dir}/Squasher_2.sv" ]\
 [file normalize "${core_dir}/Squasher_3.sv" ]\
 [file normalize "${core_dir}/Squasher_4.sv" ]\
 [file normalize "${core_dir}/Squasher_6.sv" ]\
 [file normalize "${core_dir}/Squasher_7.sv" ]\
 [file normalize "${core_dir}/Squasher_8.sv" ]\
 [file normalize "${core_dir}/Squasher_9.sv" ]\
 [file normalize "${core_dir}/Squasher.sv" ]\
 [file normalize "${core_dir}/sram_array_1p1024x64m64s1h1l2_l2_dat.sv" ]\
 [file normalize "${core_dir}/sram_array_1p128x136m34s1h0l1_l2_tag.sv" ]\
 [file normalize "${core_dir}/sram_array_1p128x16m16s1h0l1_l2_repl.sv" ]\
 [file normalize "${core_dir}/sram_array_1p128x20m10s1h0l1_bp_ftb.sv" ]\
 [file normalize "${core_dir}/sram_array_1p128x20m10s1h0l1_bp_tage.sv" ]\
 [file normalize "${core_dir}/sram_array_1p128x56m7s1h0l1_l2_meta.sv" ]\
 [file normalize "${core_dir}/sram_array_1p128x72m1s1h0l1_bp_ittage.sv" ]\
 [file normalize "${core_dir}/sram_array_1p128x8m1s1h0l1_l2_orgb.sv" ]\
 [file normalize "${core_dir}/sram_array_1p256x2m1s1h0l1_bp_tage_us.sv" ]\
 [file normalize "${core_dir}/sram_array_1p256x4m1s1h0l1_bp_tage_us.sv" ]\
 [file normalize "${core_dir}/sram_array_1p32x74m37s1h0l1_icsh_tag.sv" ]\
 [file normalize "${core_dir}/sram_array_1p4x392m98s1h0l1_ptw_l1.sv" ]\
 [file normalize "${core_dir}/sram_array_1p4x456m114s1h0l1_ptw_l0.sv" ]\
 [file normalize "${core_dir}/sram_array_1p64x20m10s1h0l1_bp_tage.sv" ]\
 [file normalize "${core_dir}/sram_array_1p64x66m66s1h0l1_icsh_dat.sv" ]\
 [file normalize "${core_dir}/sram_array_1p64x72m72s1h0l1_dcsh_dat.sv" ]\
 [file normalize "${core_dir}/sram_array_1p64x86m43s1h0l1_dcsh_tag.sv" ]\
 [file normalize "${core_dir}/sram_array_2p256x16m2s1h0l1_bp_tage_bt.sv" ]\
 [file normalize "${core_dir}/sram_array_2p64x24m6s1h0l1_bp_sc.sv" ]\
 [file normalize "${core_dir}/sram_array_2p8x80m80s1h0l1_ftq.sv" ]\
 [file normalize "${core_dir}/SRAMTemplate_135.sv" ]\
 [file normalize "${core_dir}/SRAMTemplate_151.sv" ]\
 [file normalize "${core_dir}/SRAMTemplate_155.sv" ]\
 [file normalize "${core_dir}/SRAMTemplate_163.sv" ]\
 [file normalize "${core_dir}/SRAMTemplate_165.sv" ]\
 [file normalize "${core_dir}/SRAMTemplate_166.sv" ]\
 [file normalize "${core_dir}/SRAMTemplate_167.sv" ]\
 [file normalize "${core_dir}/SRAMTemplate_168.sv" ]\
 [file normalize "${core_dir}/SRAMTemplate_189.sv" ]\
 [file normalize "${core_dir}/SRAMTemplate_197.sv" ]\
 [file normalize "${core_dir}/SRAMTemplate_198.sv" ]\
 [file normalize "${core_dir}/SRAMTemplate_199.sv" ]\
 [file normalize "${core_dir}/SRAMTemplate_200.sv" ]\
 [file normalize "${core_dir}/SRAMTemplate_201.sv" ]\
 [file normalize "${core_dir}/SRAMTemplate_36.sv" ]\
 [file normalize "${core_dir}/SRAMTemplate_44.sv" ]\
 [file normalize "${core_dir}/SRAMTemplate_45.sv" ]\
 [file normalize "${core_dir}/SRAMTemplate_4.sv" ]\
 [file normalize "${core_dir}/SRAMTemplate_54.sv" ]\
 [file normalize "${core_dir}/SRAMTemplate_55.sv" ]\
 [file normalize "${core_dir}/SRAMTemplate_59.sv" ]\
 [file normalize "${core_dir}/SRAMTemplate_61.sv" ]\
 [file normalize "${core_dir}/SRAMTemplate_63.sv" ]\
 [file normalize "${core_dir}/SRAMTemplate_65.sv" ]\
 [file normalize "${core_dir}/SRAMTemplate_67.sv" ]\
 [file normalize "${core_dir}/SRAMTemplate_71.sv" ]\
 [file normalize "${core_dir}/SRAMTemplate.sv" ]\
 [file normalize "${core_dir}/SRAMTemplateWithFixedWidth.sv" ]\
 [file normalize "${core_dir}/SRAMWrapper.sv" ]\
 [file normalize "${core_dir}/SretEventModule.sv" ]\
 [file normalize "${core_dir}/SrnctlModule.sv" ]\
 [file normalize "${core_dir}/SRT16DividerDataModule.sv" ]\
 [file normalize "${core_dir}/SRT16Divint_4.sv" ]\
 [file normalize "${core_dir}/SRT16Divint_6.sv" ]\
 [file normalize "${core_dir}/SRT16Divint.sv" ]\
 [file normalize "${core_dir}/SRT4qdsCons.sv" ]\
 [file normalize "${core_dir}/SscratchModule.sv" ]\
 [file normalize "${core_dir}/SstateenModule.sv" ]\
 [file normalize "${core_dir}/SstcInterruptGen.sv" ]\
 [file normalize "${core_dir}/Stamper.sv" ]\
 [file normalize "${core_dir}/StdFreeList_1.sv" ]\
 [file normalize "${core_dir}/StdFreeList_2.sv" ]\
 [file normalize "${core_dir}/StdFreeList_3.sv" ]\
 [file normalize "${core_dir}/StdFreeList.sv" ]\
 [file normalize "${core_dir}/Std.sv" ]\
 [file normalize "${core_dir}/StimecmpModule.sv" ]\
 [file normalize "${core_dir}/StopeiModule.sv" ]\
 [file normalize "${core_dir}/StopiModule.sv" ]\
 [file normalize "${core_dir}/StoreExceptionBuffer.sv" ]\
 [file normalize "${core_dir}/StoreMisalignBuffer.sv" ]\
 [file normalize "${core_dir}/StorePfWrapper.sv" ]\
 [file normalize "${core_dir}/StorePrefetchBursts.sv" ]\
 [file normalize "${core_dir}/StoreQueue.sv" ]\
 [file normalize "${core_dir}/StoreUnit.sv" ]\
 [file normalize "${core_dir}/strdiedLSNumOfUopTable.sv" ]\
 [file normalize "${core_dir}/StvalModule.sv" ]\
 [file normalize "${core_dir}/StvecModule.sv" ]\
 [file normalize "${core_dir}/SubDirectory.sv" ]\
 [file normalize "${core_dir}/SubModule.sv" ]\
 [file normalize "${core_dir}/SyncDataModuleTemplate__64entry.sv" ]\
 [file normalize "${core_dir}/SyncDataModuleTemplate__8entry_1.sv" ]\
 [file normalize "${core_dir}/SyncDataModuleTemplate__8entry_2.sv" ]\
 [file normalize "${core_dir}/SyncDataModuleTemplate__8entry_3.sv" ]\
 [file normalize "${core_dir}/SyncDataModuleTemplate__8entry.sv" ]\
 [file normalize "${core_dir}/SyncDataModuleTemplate_BackendPC_8entry.sv" ]\
 [file normalize "${core_dir}/SyncDataModuleTemplate_FtqPC_8entry.sv" ]\
 [file normalize "${core_dir}/TagArray.sv" ]\
 [file normalize "${core_dir}/TageBTable.sv" ]\
 [file normalize "${core_dir}/Tage_SC.sv" ]\
 [file normalize "${core_dir}/TageTable_1.sv" ]\
 [file normalize "${core_dir}/TageTable_2.sv" ]\
 [file normalize "${core_dir}/TageTable.sv" ]\
 [file normalize "${core_dir}/TagSRAMBank.sv" ]\
 [file normalize "${core_dir}/Tdata1Module.sv" ]\
 [file normalize "${core_dir}/Tdata2Module.sv" ]\
 [file normalize "${core_dir}/timeModule.sv" ]\
 [file normalize "${core_dir}/TL2TLCoupledL2.sv" ]\
 [file normalize "${core_dir}/TLAsyncCrossingSink.sv" ]\
 [file normalize "${core_dir}/TLAsyncCrossingSource.sv" ]\
 [file normalize "${core_dir}/TLBFA_1.sv" ]\
 [file normalize "${core_dir}/TLBFA_2.sv" ]\
 [file normalize "${core_dir}/TLBFA_3.sv" ]\
 [file normalize "${core_dir}/TLBFA.sv" ]\
 [file normalize "${core_dir}/TLBNonBlock_1.sv" ]\
 [file normalize "${core_dir}/TLBNonBlock_2.sv" ]\
 [file normalize "${core_dir}/TLBNonBlock.sv" ]\
 [file normalize "${core_dir}/TlbStorageWrapper_1.sv" ]\
 [file normalize "${core_dir}/TlbStorageWrapper_2.sv" ]\
 [file normalize "${core_dir}/TlbStorageWrapper_3.sv" ]\
 [file normalize "${core_dir}/TlbStorageWrapper.sv" ]\
 [file normalize "${core_dir}/TLB.sv" ]\
 [file normalize "${core_dir}/TLBuffer_10.sv" ]\
 [file normalize "${core_dir}/TLBuffer_14.sv" ]\
 [file normalize "${core_dir}/TLBuffer_15.sv" ]\
 [file normalize "${core_dir}/TLBuffer_16.sv" ]\
 [file normalize "${core_dir}/TLBuffer_20.sv" ]\
 [file normalize "${core_dir}/TLBuffer_21.sv" ]\
 [file normalize "${core_dir}/TLBuffer_22.sv" ]\
 [file normalize "${core_dir}/TLBuffer_23.sv" ]\
 [file normalize "${core_dir}/TLBuffer_27.sv" ]\
 [file normalize "${core_dir}/TLBuffer_29.sv" ]\
 [file normalize "${core_dir}/TLBuffer_2.sv" ]\
 [file normalize "${core_dir}/TLBuffer_5.sv" ]\
 [file normalize "${core_dir}/TLBuffer_7.sv" ]\
 [file normalize "${core_dir}/TLBuffer.sv" ]\
 [file normalize "${core_dir}/TLBusBypassBar.sv" ]\
 [file normalize "${core_dir}/TLBusBypass.sv" ]\
 [file normalize "${core_dir}/TLCacheCork.sv" ]\
 [file normalize "${core_dir}/TLClientsMerger_1.sv" ]\
 [file normalize "${core_dir}/TLClientsMerger.sv" ]\
 [file normalize "${core_dir}/TLDebugModuleInnerAsync.sv" ]\
 [file normalize "${core_dir}/TLDebugModuleInner.sv" ]\
 [file normalize "${core_dir}/TLDebugModuleOuterAsync.sv" ]\
 [file normalize "${core_dir}/TLDebugModuleOuter.sv" ]\
 [file normalize "${core_dir}/TLDebugModule.sv" ]\
 [file normalize "${core_dir}/TLError_1.sv" ]\
 [file normalize "${core_dir}/TLError.sv" ]\
 [file normalize "${core_dir}/TLFIFOFixer.sv" ]\
 [file normalize "${core_dir}/TLPLIC.sv" ]\
 [file normalize "${core_dir}/TLPMA.sv" ]\
 [file normalize "${core_dir}/TLToAXI4_1.sv" ]\
 [file normalize "${core_dir}/TLToAXI4.sv" ]\
 [file normalize "${core_dir}/TLWidthWidget_2.sv" ]\
 [file normalize "${core_dir}/TLWidthWidget.sv" ]\
 [file normalize "${core_dir}/TLXbar_1.sv" ]\
 [file normalize "${core_dir}/TLXbar_2.sv" ]\
 [file normalize "${core_dir}/TLXbar_3.sv" ]\
 [file normalize "${core_dir}/TLXbar_5.sv" ]\
 [file normalize "${core_dir}/TLXbar_6.sv" ]\
 [file normalize "${core_dir}/TLXbar_7.sv" ]\
 [file normalize "${core_dir}/TLXbar_8.sv" ]\
 [file normalize "${core_dir}/TLXbar_9.sv" ]\
 [file normalize "${core_dir}/TLXbar.sv" ]\
 [file normalize "${core_dir}/TraceBuffer.sv" ]\
 [file normalize "${core_dir}/Trace.sv" ]\
 [file normalize "${core_dir}/TrapEntryDEventModule.sv" ]\
 [file normalize "${core_dir}/TrapEntryHSEventModule.sv" ]\
 [file normalize "${core_dir}/TrapEntryMEventModule.sv" ]\
 [file normalize "${core_dir}/TrapEntryMNEventModule.sv" ]\
 [file normalize "${core_dir}/TrapEntryVSEventModule.sv" ]\
 [file normalize "${core_dir}/TrapHandleModule.sv" ]\
 [file normalize "${core_dir}/TrapInstMod.sv" ]\
 [file normalize "${core_dir}/TrapTvalMod.sv" ]\
 [file normalize "${core_dir}/TreeArbiter.sv" ]\
 [file normalize "${core_dir}/Trigger0_Tdata1Module.sv" ]\
 [file normalize "${core_dir}/Trigger0_Tdata2Module.sv" ]\
 [file normalize "${core_dir}/Trigger1_Tdata1Module.sv" ]\
 [file normalize "${core_dir}/Trigger1_Tdata2Module.sv" ]\
 [file normalize "${core_dir}/Trigger2_Tdata1Module.sv" ]\
 [file normalize "${core_dir}/Trigger2_Tdata2Module.sv" ]\
 [file normalize "${core_dir}/Trigger3_Tdata1Module.sv" ]\
 [file normalize "${core_dir}/Trigger3_Tdata2Module.sv" ]\
 [file normalize "${core_dir}/TselectModule.sv" ]\
 [file normalize "${core_dir}/UIntCompressor_27_000000000000001010100000000.sv" ]\
 [file normalize "${core_dir}/UIntCompressor_27_000011100000000000001010101.sv" ]\
 [file normalize "${core_dir}/UIntExtractor_27_000000000000001010100000000.sv" ]\
 [file normalize "${core_dir}/UIntExtractor_27_000011100000000000001010101.sv" ]\
 [file normalize "${core_dir}/UIntToContLow0s.sv" ]\
 [file normalize "${core_dir}/UIntToContLow1s.sv" ]\
 [file normalize "${core_dir}/UncacheEntry_1.sv" ]\
 [file normalize "${core_dir}/UncacheEntry_2.sv" ]\
 [file normalize "${core_dir}/UncacheEntry_3.sv" ]\
 [file normalize "${core_dir}/UncacheEntry_4.sv" ]\
 [file normalize "${core_dir}/UncacheEntry_5.sv" ]\
 [file normalize "${core_dir}/UncacheEntry_6.sv" ]\
 [file normalize "${core_dir}/UncacheEntry_7.sv" ]\
 [file normalize "${core_dir}/UncacheEntry.sv" ]\
 [file normalize "${core_dir}/Uncache.sv" ]\
 [file normalize "${core_dir}/UopInfoGen.sv" ]\
 [file normalize "${core_dir}/V0RegFilePart0.sv" ]\
 [file normalize "${core_dir}/V0RegFilePart1.sv" ]\
 [file normalize "${core_dir}/V0RFReadArbiter.sv" ]\
 [file normalize "${core_dir}/V0RFWBCollideChecker.sv" ]\
 [file normalize "${core_dir}/Validator.sv" ]\
 [file normalize "${core_dir}/VcsrModule.sv" ]\
 [file normalize "${core_dir}/VCVT_1.sv" ]\
 [file normalize "${core_dir}/VCVT_2.sv" ]\
 [file normalize "${core_dir}/VCVT_8.sv" ]\
 [file normalize "${core_dir}/VCVT.sv" ]\
 [file normalize "${core_dir}/VecDataSplitModule.sv" ]\
 [file normalize "${core_dir}/VecExceptionGen.sv" ]\
 [file normalize "${core_dir}/VecExcpDataMergeModule.sv" ]\
 [file normalize "${core_dir}/VectorCvt.sv" ]\
 [file normalize "${core_dir}/VectorCvtTop.sv" ]\
 [file normalize "${core_dir}/VectorFloatAdder.sv" ]\
 [file normalize "${core_dir}/VectorFloatDividerR64.sv" ]\
 [file normalize "${core_dir}/VectorFloatDivider.sv" ]\
 [file normalize "${core_dir}/VectorFloatFMA.sv" ]\
 [file normalize "${core_dir}/VectorIdiv.sv" ]\
 [file normalize "${core_dir}/VFAlu.sv" ]\
 [file normalize "${core_dir}/VFDivSqrt.sv" ]\
 [file normalize "${core_dir}/VFixPoint64b.sv" ]\
 [file normalize "${core_dir}/VFMA.sv" ]\
 [file normalize "${core_dir}/VfofBuffer.sv" ]\
 [file normalize "${core_dir}/VfRegFilePart0.sv" ]\
 [file normalize "${core_dir}/VfRegFilePart1.sv" ]\
 [file normalize "${core_dir}/VfRegFilePart2.sv" ]\
 [file normalize "${core_dir}/VfRegFilePart3.sv" ]\
 [file normalize "${core_dir}/VfRFReadArbiter.sv" ]\
 [file normalize "${core_dir}/VfRFWBCollideChecker.sv" ]\
 [file normalize "${core_dir}/VIAluDecoder.sv" ]\
 [file normalize "${core_dir}/VIAluFix.sv" ]\
 [file normalize "${core_dir}/VIAluSrcTypeModule.sv" ]\
 [file normalize "${core_dir}/VIAlu.sv" ]\
 [file normalize "${core_dir}/VIDiv.sv" ]\
 [file normalize "${core_dir}/VIMac64b.sv" ]\
 [file normalize "${core_dir}/VIMacSrcTypeModule.sv" ]\
 [file normalize "${core_dir}/VIMacU.sv" ]\
 [file normalize "${core_dir}/VIntAdder64b.sv" ]\
 [file normalize "${core_dir}/VIntFixpAlu64b.sv" ]\
 [file normalize "${core_dir}/VIntMisc64b.sv" ]\
 [file normalize "${core_dir}/VIPU.sv" ]\
 [file normalize "${core_dir}/VirtualLevelPermitModule.sv" ]\
 [file normalize "${core_dir}/VirtualLoadQueue.sv" ]\
 [file normalize "${core_dir}/VlBusyTable.sv" ]\
 [file normalize "${core_dir}/VldMergeUnit.sv" ]\
 [file normalize "${core_dir}/VldMgu.sv" ]\
 [file normalize "${core_dir}/VLMergeBufferImp.sv" ]\
 [file normalize "${core_dir}/VlRegFile.sv" ]\
 [file normalize "${core_dir}/VlRFReadArbiter.sv" ]\
 [file normalize "${core_dir}/VlRFWBCollideChecker.sv" ]\
 [file normalize "${core_dir}/VLSplitBufferImp.sv" ]\
 [file normalize "${core_dir}/VLSplitImp.sv" ]\
 [file normalize "${core_dir}/VLSplitPipelineImp.sv" ]\
 [file normalize "${core_dir}/VMask.sv" ]\
 [file normalize "${core_dir}/VPermSrcTypeModule.sv" ]\
 [file normalize "${core_dir}/VPPU.sv" ]\
 [file normalize "${core_dir}/VSatpModule.sv" ]\
 [file normalize "${core_dir}/VScauseModule.sv" ]\
 [file normalize "${core_dir}/VSegmentTrigger.sv" ]\
 [file normalize "${core_dir}/VSegmentUnit.sv" ]\
 [file normalize "${core_dir}/VSepcModule.sv" ]\
 [file normalize "${core_dir}/VsetModule.sv" ]\
 [file normalize "${core_dir}/VSetRiWi.sv" ]\
 [file normalize "${core_dir}/VSetRiWvf.sv" ]\
 [file normalize "${core_dir}/VSetRvfWvf.sv" ]\
 [file normalize "${core_dir}/VSieModule.sv" ]\
 [file normalize "${core_dir}/VSipModule.sv" ]\
 [file normalize "${core_dir}/VSiregModule.sv" ]\
 [file normalize "${core_dir}/VSiselectModule.sv" ]\
 [file normalize "${core_dir}/VSMergeBufferImp.sv" ]\
 [file normalize "${core_dir}/VSscratchModule.sv" ]\
 [file normalize "${core_dir}/VSSplitBufferImp.sv" ]\
 [file normalize "${core_dir}/VSSplitImp.sv" ]\
 [file normalize "${core_dir}/VSSplitPipelineImp.sv" ]\
 [file normalize "${core_dir}/VSstatusModule.sv" ]\
 [file normalize "${core_dir}/VstartModule.sv" ]\
 [file normalize "${core_dir}/VStimecmpModule.sv" ]\
 [file normalize "${core_dir}/VStopeiModule.sv" ]\
 [file normalize "${core_dir}/VStopiModule.sv" ]\
 [file normalize "${core_dir}/VStvalModule.sv" ]\
 [file normalize "${core_dir}/VStvecModule.sv" ]\
 [file normalize "${core_dir}/VTypeBuffer.sv" ]\
 [file normalize "${core_dir}/VTypeGen.sv" ]\
 [file normalize "${core_dir}/VtypeModule.sv" ]\
 [file normalize "${core_dir}/WayLookup.sv" ]\
 [file normalize "${core_dir}/WBArbiter_1.sv" ]\
 [file normalize "${core_dir}/WBArbiter_2.sv" ]\
 [file normalize "${core_dir}/WBArbiter_30.sv" ]\
 [file normalize "${core_dir}/WBArbiter_33.sv" ]\
 [file normalize "${core_dir}/WBArbiter_38.sv" ]\
 [file normalize "${core_dir}/WBArbiter_3.sv" ]\
 [file normalize "${core_dir}/WBArbiter_41.sv" ]\
 [file normalize "${core_dir}/WBArbiter_43.sv" ]\
 [file normalize "${core_dir}/WBArbiter_55.sv" ]\
 [file normalize "${core_dir}/WBArbiter_64.sv" ]\
 [file normalize "${core_dir}/WBArbiter_65.sv" ]\
 [file normalize "${core_dir}/WBArbiter_66.sv" ]\
 [file normalize "${core_dir}/WBArbiter.sv" ]\
 [file normalize "${core_dir}/WbDataPath.sv" ]\
 [file normalize "${core_dir}/WbFuBusyTable.sv" ]\
 [file normalize "${core_dir}/WordResultSelect.sv" ]\
 [file normalize "${core_dir}/WrBypass_16.sv" ]\
 [file normalize "${core_dir}/WrBypass_24.sv" ]\
 [file normalize "${core_dir}/WrBypass_25.sv" ]\
 [file normalize "${core_dir}/WrBypass_29.sv" ]\
 [file normalize "${core_dir}/WrBypass_31.sv" ]\
 [file normalize "${core_dir}/WrBypass.sv" ]\
 [file normalize "${core_dir}/WritebackEntry_3.sv" ]\
 [file normalize "${core_dir}/WritebackEntry.sv" ]\
 [file normalize "${core_dir}/WritebackQueue.sv" ]\
 [file normalize "${core_dir}/XRetPermitModule.sv" ]\
 [file normalize "${core_dir}/XSCore.sv" ]\
 [file normalize "${core_dir}/XSDiffTop.sv" ]\
 [file normalize "${core_dir}/XSTile.sv" ]\
 [file normalize "${core_dir}/XSTop.sv" ]\
 [file normalize "${core_dir}/XSTop.sv.conf" ]\
]
