
# Usage:
# python3 send_email.py subject content
""" Should prepare yaml file, include:

user: 886@oicq.com
passwd: adfazaf # not passwordPassword code generated by the email.
# Ref_link: https://service.mail.qq.com/cgi-bin/help?subtype=1&&no=1001256&&id=28
receiver: ["886@oicq.com", "v50@hgg.com"]

"""

import sys
import os
import time

import yaml
import yagmail

def send_email(title, msg):
  try:
    yaml_file = r'email.yml'
    file = open(yaml_file, "r", encoding="utf-8")
    data = yaml.safe_load(file.read())
    file.close()

    yag = yagmail.SMTP(user=data['user'], password=data['passwd'], host="smtp.qq.com")
    yag.send(to=data["receiver"], subject=title, contents=msg)
    print("Email send success")
  except:
    print("Email send failed")