set_property PACKAGE_PIN AT4 [get_ports {pci_ep_rxp[7]}]
set_property PACKAGE_PIN AR2 [get_ports {pci_ep_rxp[6]}]
set_property PACKAGE_PIN AP4 [get_ports {pci_ep_rxp[5]}]
set_property PACKAGE_PIN AN2 [get_ports {pci_ep_rxp[4]}]
set_property PACKAGE_PIN AM4 [get_ports {pci_ep_rxp[3]}]
set_property PACKAGE_PIN AL2 [get_ports {pci_ep_rxp[2]}]
set_property PACKAGE_PIN AK4 [get_ports {pci_ep_rxp[1]}]
set_property PACKAGE_PIN AJ2 [get_ports {pci_ep_rxp[0]}]

set_property PACKAGE_PIN AV9 [get_ports {pci_ep_txp[7]}]
set_property PACKAGE_PIN AU7 [get_ports {pci_ep_txp[6]}]
set_property PACKAGE_PIN AT9 [get_ports {pci_ep_txp[5]}]
set_property PACKAGE_PIN AR7 [get_ports {pci_ep_txp[4]}]
set_property PACKAGE_PIN AP9 [get_ports {pci_ep_txp[3]}]
set_property PACKAGE_PIN AN7 [get_ports {pci_ep_txp[2]}]
set_property PACKAGE_PIN AM9 [get_ports {pci_ep_txp[1]}]
set_property PACKAGE_PIN AL7 [get_ports {pci_ep_txp[0]}]
